### PR TITLE
Chat room create rework

### PR DESCRIPTION
**Pull request by ace-1331**
should be merged after #2916 because it includes it in this PR

- reworked the entire ChatCreate screen to allow all things to be modifiable right from the start (its no longer needed to update the room after creation!)

New things that can be done on creation: ban list, admin list, locking the room

With all the inputs and text, it wasn't feasible to keep the background as the selection like before, it was atrociously ugly! To preserve the same ability to preview backgrounds, clicking the smaller background preview toggles "full screen previews"

Open to feedback on style, available features/options etc. to improve it further. (Although keeping the style consistent across ChatCreate and ChatAdmin will help simplify future changes!)
Capture

### CODE REVIEW

**Comment by Ben987** [comment]
This one has conflicts, can you resolve them and test again?  Thanks.

**Comment by ace-1331** [comment]
should be good now

**Comment by Ben987** [comment]
That one creates a conflict with other pull requests, can you resolve and test again?  Thanks!

**Comment by Ben987** [comment]
I'm curious to try this one, thanks a lot.  Et merci pour la traduction francophone.

**Pull request merged**
