### PR TITLE
OnlineProfile page

### PR DESCRIPTION
**Pull request by EveFerox**
A separate page for players info, currently only displaying a big text area for characters Description property.

requires change on server: https://github.com/Ben987/Bondage-Club-Server/pull/12

### CODE REVIEW

**Comment by Ben987** [comment]
A player info page is a good idea, I've been wanting it for a while.  Can you post some screenshots to show me out it looks in game?  Thanks.

**Comment by EveFerox** [comment]
https://gyazo.com/8e14c7f3ce7d2d79e6fa9b234527b988

https://gyazo.com/aefc4706af9dde1254dcc71e36b77151

**Comment by Ben987** [comment]
I'm sure that online players will like it.  Could you remove the code from the class and use regular functions?  Having a class there isn't needed and there aren't any classes in the code, it will create a different code structure standard.  Thanks a lot.

**Comment by EveFerox** [comment]
grr.. done >.<

**Comment by Ben987** [comment]
Thanks a lot!  I know it's not fun having to redo some code, but the project will be easier to manage with one standard.  More stuff like BDSM preferences will probably be added to that screen later, it will be useful.  Cheers.

**Pull request merged**
