### PR TITLE
some more tape for the head and mouth

### PR DESCRIPTION
**Pull request by gatetrek**
added: Akita new tape art for the head and mouth
made wrap tape into part of an extension for the head instead of its own item

### CODE REVIEW

**Comment by Ben987** [comment]
This is great!  the Mouse X & Y position doesn't seem right though.  Can you review the coordinates that you've put?  Thanks.

**Comment by gatetrek** [comment]
on which item?
if it the face cover it been moved upwards as to not cover the others
http://prntscr.com/ok9pbo

**Comment by Ben987** [comment]
Check MouseX and MouseY in InventoryItemMouthDuctTapeClick()

It doesn't seem to be correct from my side.

**Comment by gatetrek** [comment]
yeah was only the Y's that was wrong and been fixed now
thanks for pointing it out

**Comment by Ben987** [comment]
Excellent!  I'm doing the hot fixes for the current version but I will review it soon.  Thanks :)

**Comment by Ben987** [comment]
That looks great!  I'll test it soon.  Thanks :)

**Pull request merged**
