### PR TITLE
Pony harness gag

### PR DESCRIPTION
**Pull request by MoonlightGleam**
Added an over complicated pony harness gag:
Added Unicorn horn cosplay item

Special thanks to Estsanatlehi for helping with the activity modifications and some minor fixes.

### CODE REVIEW

**Comment by Ben987** [comment]
Wow!  This is HUGE!  Thanks a lot, I'm curious to try it :)

**Comment by MoonlightGleam** [comment]
> Wow! This is HUGE! Thanks a lot, I'm curious to try it :)

^^ I hope you al enjoy it

**Comment by Jomshir98** [comment]
@MoonlightGleam 
Hi! I noticed the extended config has config for all 3 mouth slots, but the actual asset exists only in the first one.
No matter which of those is correct, this surely is bug.

**Comment by MoonlightGleam** [comment]
It was intended to be added to the three slots once all the bugs and glitches where solved.
I forgot to add it to slots 2 and 3. 
If Im still on time, Ill add them tonight

**Pull request merged**
