### PR TITLE
Add enhanced arrest flow

### PR DESCRIPTION
**Pull request by backer**
Adds an enhanced arrest flow with more options and actions when the player has stolen/hidden the dice.

Details in commit messages as necessary.

In aggressive flow, instead of just asking you to follow with options to escape or follow,
add more aggressive encounter.

Cop tells player to put their hands in the air, at which point the
player can comply or try to escape and fight like normal

After putting hands in air, Police tell player to get on their knees.
This is the player's last chance to try to fight and escape.

After getting on knees, player is told to put their hands behind their
back, at which point they will be handcuffed. If they try to escape once
on their knees, the police will stop them and hogtie them.

Once the aggressive encounter ends in defeat, either through submission
or losing fight, the player is taken to the prison where the normal
event flow is followed.

Also fixes a bug in which dice would never be deleted from log if hidden after stealing.

### CODE REVIEW

**Comment by Ben987** [comment]
Hi there, have you spoken with @GIT4NICK about this change?  Or are you git4nick yourself?  He built that part of the club.  You can reach him on DeviantArt to talk with him about this PR and have him approve it.  Thanks a lot.

**Comment by backer** [comment]
@Ben987 I'll reach out to him, thanks!

**Comment by GIT4NICK** [comment]
Hello,
The change looks good. Thanks for the suggestion. I think that can be merged.

**Comment by backer** [comment]
Thanks @GIT4NICK!! @Ben987 I see this needs 2 approvals to merge. Would you do the second review and/or merge it yourself?

**Comment by Ben987** [comment]
Great!  We are in beta mode now so we are only merging fixes for a week.  But as soon as the version is stable I will review it.  Thanks you two :)

**Comment by backer** [comment]
@Ben987 sounds good!

**Comment by Ben987** [comment]
Thanks a lot you two!  @backer , I will merge it right now.  Can you test the latest master branch to see if everything works as you intended?

**Comment by backer** [comment]
@Ben987 Just tested current master and everything looks good to me! Thanks!

**Pull request merged**
