### PR TITLE
Chinese translation test

### PR DESCRIPTION
**Pull request by InDarkWings**
image

### CODE REVIEW

**Comment by Ben987** [comment]
Is this a test or it's ready to merge to master branch?  Please don't push tests to master.  Thanks.

**Comment by InDarkWings** [comment]
> 这是测试还是准备合并到master分支？请不要将测试推向高手。谢谢。

ok

**Comment by InDarkWings** [comment]
> Is this a test or it's ready to merge to master branch? Please don't push tests to master. Thanks.

ok

**Comment by Ben987** [comment]
Lets close this test for now then.  Please do the pull request to master when you're fully ready.

**Pull request closed without merging**
