### PR TITLE
Kinky Dungeon 1.34

### PR DESCRIPTION
**Pull request by Ada18980**
Includes critical fixes for extended archetype items, and also adds:
-Slime ball, a spell which launches a sticky ball that deals low damage but also leaves a sticky trail
-A slime witch who appears on levels 4 and up; she is long-ranged and quite dangerous but falters in close quarters.

### CODE REVIEW

**Comment by Ada18980** [comment]
Dependency on PR #2408

**Comment by Ben987** [comment]
This one creates a conflict with another pull request.  Can you resolve it and test again?  Thanks :)

**Comment by Ada18980** [comment]
image

Fixed...

**Comment by Ben987** [comment]
Github can have crazy conflicts from time to time.  Thanks!

**Pull request merged**
