### PR TITLE
text remove duplicate code, prefetch screens

### PR DESCRIPTION
**Pull request by NoneNoname**

### CODE REVIEW

**Comment by Ben987** [comment]
What does it change exactly?  Does it fix a bug that I can recreate?  Thanks.

**Comment by NoneNoname** [comment]
prefetch as it loads the text before the user switch to a page this helps to remove a short flesh when texts are empty
this is not a bugfix (improvement label)

**Comment by Ben987** [comment]
Have you also tested with translated texts?

**Comment by NoneNoname** [comment]
yes, I tested this with other languages too, and other than the prefetch other parts were already existing and were tested for a long time
as for the English, I have been using this prefetch for the last month or so and it works great

**Comment by Ben987** [comment]
Awesome!  It's time to test it then.  Thanks a lot :)

**Pull request merged**
