### PR TITLE
Refactor: Chains (ItemFeet)

### PR DESCRIPTION
**Pull request by ace-1331**
- refactored the itemfeet chains to use the extended script

### CODE REVIEW

**Review by elliesec — APPROVED** [review]

**Review by Nina-1474 — CHANGES_REQUESTED** [review]
Since this item has a Validate function, the Prerequisite aren't being checked within ExtendedItem.
The reasoning is an item may want to handle prereqs in its own way, for example Web which needs to ensure the prereq isn't caused by itself. The usual preqreq checks will need to be covered in this item's Validate.

**Comment by ace-1331** [comment]
Used the same process as the web, should be ok

**Comment by elliesec** [comment]
Just fixed a couple of little things - I'll pull it down to test soon.

**Comment by Nina-1474** [comment]
Since the options don't have two types that block each other (unlike the web which has seperate types with SetPose: Suspension and Prerequisite: NotSuspended), I don't think the removal and reapplication of the item in Validate is actually necessary.

**Comment by ace-1331** [comment]
sure, as long as no one forgets about it if/when more types are added (though arguably, that should be handled in inventory allow

**Review by Nina-1474 — APPROVED** [review]
Made a small fix to add the character line back in. All good!

**Pull request merged**
