### PR TITLE
Merging Open and Closed Back Belts

### PR DESCRIPTION
**Pull request by Nythaleath**
Made the Open and closed back belts one item that is toggleable, not able to change it while locked

### CODE REVIEW

**Comment by Ben987** [comment]
Since the scripts are similar, is there a way we could reuse the item code instead of duplicating it?  Like having one function that would handle the clicks of all belts.  Another one that would run all belts, etc.

That way if we change or fix something in the code, it would change it for every belts.

Thanks a lot.

**Comment by Nythaleath** [comment]
I dont see how I could do that, so maybe its possible but is beyond my capabilities sorry

**Comment by Nythaleath** [comment]
There the ornate, polished and studded belts now just call the Metal chastity belt's functions

**Comment by Ben987** [comment]
Awesome!  It will be easier to fix bugs in 1 spot instead of 4 in the future, thanks a lot :)

**Pull request merged**
