### PR TITLE
[Asset] [Natsuki]: Bracelets

### PR DESCRIPTION
**Pull request by Codefreak64**
So far gloves and mittens were the only thing to decorate your hands, but with bracelets its now much easier and simpler:

-Adds New Asset Type: Bracelet
-Adds 3 Bracelets to the game (Bow Band, Kinky Band, 5 Color Band)
-Wardobes now have its own bracelet tab
-Shop now has a Tab to buy Bracelets

### CODE REVIEW

**Comment by Codefreak64** [comment]
the kinky band is supposed to look like a metal ballgag
and the 5 color band is the Lesbian pride flag

**Comment by Codefreak64** [comment]
I'm getting an error on a file that I never have touched, the Lint check is the error. I would like this in before beta

**Comment by Ben987** [comment]
Thanks for adding bracelets, it's a good idea.  There's a few conflicts with other changes.  Can you resolve the conflicts and test again?   Cheers :)

**Comment by Codefreak64** [comment]
I swear i was unaware that github would pull the "add its own code" BS again on me. all are fixed and BETA ready

**Comment by Ben987** [comment]
Right on time for the next beta.  Thanks :)

**Pull request merged**
