### PR TITLE
Fix: Leash actions with lover/owner lock on leash

### PR DESCRIPTION
**Pull request by wultir**
Fixes a few checks for lover/owner lock on leash when holding or pulling into a room.

- Currently tries to get the lock from `Player.Appearance` instead of the target player which makes it unlikely that the lock is found on the sender side which allows the sender to use the hold leash action even if owner/lover locked (unless prevented by other permissions on the leashed player).
- The check when the target receives the leash messages checks against the local player and not the sender, causing the check to succeed even if lover/owner locked.

### CODE REVIEW

**Comment by Ben987** [comment]
@Ada18980 , can you validate this fix and let me know if it works as you want it?  Thanks a lot.

**Comment by Ada18980** [comment]
I have tested it and it works as expected! Just need @wultir  to resolve conflicts.

**Comment by wultir** [comment]
Updated with conflicts resolved.

**Comment by Ben987** [comment]
Thanks @wultir , there's still a conflict with Ada's latest pull request though.  Can you resolve it and test on your side?  Let me know when it's ready.  Cheers :)

**Comment by wultir** [comment]
@Ben987, I've fixed the conflicts with the latest changes. Should be good to go now.

**Comment by Ben987** [comment]
That was really quick.  Thanks a lot!

**Pull request merged**
