### PR TITLE
Refactor: Ceiling shackles to new archetypes

### PR DESCRIPTION
**Pull request by SandrineBC**
# Description
Refactors the ceiling shackles to the new archetypes

# Testing
Was done on my local installation of the club

### CODE REVIEW

**Review by jomshir98 — CHANGES_REQUESTED** [review]
The reason I didn't yet convert my item into new archetype is this line:
```js
var msg = "CeilingShacklesRestrain" + (C.Pose.includes("Suspension") ? "Suspension" : "") + Option.Name;
```
Your change would break "Suspension" behaviour of the shackles.

**Comment by SandrineBC** [comment]
> The reason I didn't yet convert my item into new archetype is this line:
> 
> ```js
> var msg = "CeilingShacklesRestrain" + (C.Pose.includes("Suspension") ? "Suspension" : "") + Option.Name;
> ```
> 
> Your change would break "Suspension" behaviour of the shackles.

Good point.

**Comment by elliesec** [comment]
For that behaviour, you might want to grab the latest master. You can now pass a function into `Config.Dialog.ChatPrefix` that would allow you to replicate the current behaviour (although you'll need to modify `TypedItem.js` slightly to pass the reference to `C` into the function when it gets called (see `TypedItemCreatePublishFunction`).

**Comment by Ben987** [comment]
Sure!  Thanks again :)

**Pull request merged**
