### PR TITLE
German Translation Updates

### PR DESCRIPTION
**Pull request by adokilume**
Once again, keeping the translation files up to date and adding new ones. I already made it so this will be compatible with FeuertinKira's typo fixes from #421 .

### CODE REVIEW

**Comment by Ben987** [comment]
Perfect!  Thanks a lot.

**Comment by Ben987** [comment]
I haven't done my proof reading though, so there might a few changes, but we can cover them later, cheers!

**Comment by adokilume** [comment]
That's alright from my side. Revising the translation files after you've done the proof reading won't be a problem. I'd rather do these more frequently and change things multiple times than wait a few weeks and have thousands of lines to do at once. :)

**Comment by Ben987** [comment]
Very well.  There's usually not that many changes after proof reading anyway,

**Pull request merged**
