### PR TITLE
Hair accessories extension

### PR DESCRIPTION
**Pull request by Nythaleath**
i was requested by a few people in the club to see if i could get multiple hair accessories to work at once
what i did:
-renamed HairAccessory to HairAccessory1
-added second hair accessory clothing slot HairAccessory2
-moved the bow, ribbons, and flower to hair accessories
-made hair accessories be bought for both categories when buying one

### CODE REVIEW

**Comment by Ben987** [comment]
That's a good idea.  What if the player already bought hair accessories from the shop?  She will lose them and have to buy it again?

**Comment by Nythaleath** [comment]
yes she would unfortunately have to but this is also intentional as buying them again will buy them for both slots, and i couldn't see how to have the same effect any other way

**Comment by gatetrek** [comment]
wouldnt leaving it called HairAccessory,  let people keep them and the other instead of being called 2 but 1 instead?

**Comment by Ben987** [comment]
Sweet!  I'll test it right now.  Thanks a lot.

**Pull request merged**
