### PR TITLE
HiddenItem rework

### PR DESCRIPTION
**Pull request by NoneNoname**
Since layers now have priority, ItemHidden no longer has a purpose, they do not allow color update and they require extra workarounds while they work like layers, we should only have one way to express one functionality so it is more simple to keep bugs away.

Added functionality to Layers:
HideAs: layers now can be hidden just like items or groups this allow the exact behavior as the previous
Top, Left:  allow other image size and position for layers

### CODE REVIEW

**Comment by elliesec** [comment]
Might be worth checking with @Nina-1474 that the suspension ropes/chains in `ItemHidden` are okay to remove or whether that's going to cause pain for her upcoming variable suspension height changes.

**Comment by Nina-1474** [comment]
I've moved the ItemHidden rope/chains to layers in my local branch in very much the same way as here, so I'm good to work with this.
Thanks Ellie!

Also a heads up, most of SetPose cleanups will conflict with #1326 which replaces them with ExtendedItem calls.

**Comment by elliesec** [comment]
I figured that might be the case, but just wanted to double-check!

**Comment by Ben987** [comment]
I'm glad to see a new change from you, it's been a while, cheers!  I don't know if you still check Discord, but developers will be able to approve pull request in a near future, so yours will probably be reviewed by Ace, Nina, Ellie, Kira or Ayesha, check the Discord channel for more detail.  Welcome back!

**Review by ace-1331 — APPROVED** [review]
Looks good, nice to finally get rid of this group.

When multi color is added, we can add the straps to the colorable stuff (#1368)

**Review by elliesec — APPROVED** [review]

**Pull request merged**
