### PR TITLE
Fix: Draw fix.

### PR DESCRIPTION
**Pull request by remiliacn**
## What is this change?

Fix the issue where the text does not wrap correctly when using Chinese language.

### Before (English)
3 - origin

### Before (Chinese)
4 - origin

### After (Chinese)
image

### CODE REVIEW

**Comment by Nina-1474** [comment]
This will cause English words to end up split across two lines.

**Comment by remiliacn** [comment]
> This will cause English words to end up split across two lines.

Yes you are right. I was thinking how to fix that just now.

**Comment by zorgjbe** [comment]
You're carrying around a bunch of unrelated commits (the ones from the OOC refactor) as well. I guess you might want to make sure your master is in sync with upstream, then rebase that draw_fix branch on top of it.

**Comment by remiliacn** [comment]
Making it to a draft for now until I found something feasible to handle both English and Chinese.

**Pull request closed without merging**
