### PR TITLE
Enhanced color picker

### PR DESCRIPTION
**Pull request by vsanvsan**
A enhanced color picker based on HSV color model (like color picker in photoshop)

### CODE REVIEW

**Comment by Ben987** [comment]
That looks interesting.  Can you post a few screenshots demonstrating the in-game results?  I'd love a better color picker.  Thanks!

**Comment by vsanvsan** [comment]
> That looks interesting. Can you post a few screenshots demonstrating the in-game results? I'd love a better color picker. Thanks!

Here are some screenshots:

1. Profile Screen:

image

2. Appearance Screen:

image

3. Dialog Screen:

image

**Comment by Ben987** [comment]
The timing is good, I need to prepare a second beta, I'll include it in it.  Thanks a lot, I'm curious to try it.

**Comment by Ben987** [comment]
@vsanvsan , just open a new pull request when the bugs are fixed and I'll review it again.  Thanks.

**Comment by vsanvsan** [comment]
NP, I'll fix them ASAP

**Pull request merged**
