### PR TITLE
2new dress and long strap Sandals

### PR DESCRIPTION
**Pull request by gatetrek**
2new dress and long strap Sandals with some fixes
added an alpha mask to the cages so people can have there tails and wings and also to the horse so close don't go through it

### CODE REVIEW

**Comment by Ben987** [comment]
Why is the item name "Sandels", shouldn't it be "Sandals" ?  Can you rename it and rename the images?  Thanks

**Comment by Ben987** [comment]
One last thing.  Could you name the item "Dress1" instead of "Dress".  I'm pretty sure that "Dress" will be used again.  Thanks a lot.

**Comment by gatetrek** [comment]
sure but any chance I can do that after it's been pulled so be easer to redo them and send up?

**Comment by Ben987** [comment]
Sure, just do another pull request for Dress1, I'll merge that one right now.  Thanks again!

**Pull request merged**
