### PR TITLE
Fix: Wrong csv ids for assets

### PR DESCRIPTION
**Pull request by ace-1331**
After running a script (done by noname) to check which items were missing their description in the CSV, 8 were found and corrected in this PR. All of them had the wrong name/id in the file so they were properly replaced to make sure they were not missing.

### CODE REVIEW

**Comment by ace-1331** [comment]
For clarity here is the result of the search:
Non-existing items found in the CSV file: [
    'ClothMistressTop1',
    'SuitSeethroughSuitzip',
    'TailStrapsSuccubusStrap2',
    'BodyUpperXlarge',
    'BodyLowerXlarge',
    'ItemButtHorseButtPlug',
    'ItemButtRaccoon Butt Plug',
    'ItemButtVibratingButtPlug',
    'ItemNipplesTapeVibeEggs'
  ],
  Existing items with no CSV counterpart: [
    'ClothMistressTop',
    'SuitSeethroughSuitZip',
    'TailStrapsSuccubusTailStrap',
    'BodyUpperXLarge',
    'BodyLowerXLarge',
    'ItemButtHorsetailPlug',
    'ItemButtRaccoonButtPlug',
    'ItemButtVibratingButtplug',
    'ItemNipplesTapedVibeEggs'
  ]

**Comment by Ben987** [comment]
Are you sure about that one?  I've tested a few of them and the descriptions are showing properly in-game.

**Comment by ace-1331** [comment]
I assume the ones that were just about capital letters showed before, but after fixing them, the ones clearly labeled incorrectly like the spaces, etc. Showed as intended. Just do a quick search and you will see stuff like "MistressTop1" does not exist in Female3DCG.js and "MistressTop" does not exist in the csv, and so on

**Comment by Ben987** [comment]
I've just tested a few items and the description shows properly.  What's the bug in-game?

**Comment by ace-1331** [comment]
The current CSV file requires the exact order to prevent incoherent ids like this. If they are fixed, we can stop ignoring the middle column like it is currently. Which would solve many incompatibilities issues in the future with merges and stuff, only one item would be broken instead of all the ones below it.

This is a quality cleanup more than a "bug fix". With actual consistency the rest can be improved in the future... otherwise this column can just be deleted and it would make no difference.

**Comment by Ben987** [comment]
Alright.  And you've tested the items with that version to make sure it doesn't create any new bugs?

**Comment by ace-1331** [comment]
yes, csv loads and all assets still have the correct description. This will prevent errors the day things are arranged or improved

**Comment by Ben987** [comment]
Excellent, I'll merge it then.

**Pull request merged**
