### PR TITLE
Milk pump

### PR DESCRIPTION
**Pull request by Codefreak64**
Adds 1 Item for the Nipples: Lactation Pump

Supports Standing and All fours poses, Directed towards Milk and Hucow Kinks

Tested and ready for public

Deletetions shown are showing the addition of  (HideItem: ["LactationPump],) to the item (because clipping)

Created and Coded by Z-freak(Natsuki)

### CODE REVIEW

**Comment by Codefreak64** [comment]
both are needed for the full item

**Comment by ace-1331** [comment]
You're trying to push your vscode config file in the .vscode folder. Ellie made PR #1043 to add it to git ignore so  Id recommend merging Ellie's PR first or remove the file(s) from your pull request.

**Comment by Ben987** [comment]
Please don't push .vscode/launch.json to the master branch, this is related to your IDE.

Also, if you add new entries to the player CSV file, please don't name them "off" but use something that's more specific to your item, like: YourItemName + FeatureName + Off.   "Off" could be used for tons of stuff.

One last thing, this pull request creates many conflicts with files that were changed by other pull requests.  Can you resolve the conflicts and test?

Thanks a lot

**Comment by Nina-1474** [comment]
Also minor typo in the NipPowloosensTo0 line in Dialog_Player.csv: the word "latctation" has an extra t.

**Comment by elliesec** [comment]
And a quick note - if you merge in the current master now, you'll find that the `.vscode` directory is now in the `.gitignore`, so git will no longer automatically track changes to that directory. However, as you've already committed it on your branch, git probably will still track it. You can remedy that using `git rm`:

```
git rm -r --cached .vscode
git commit "Removes .vscode directory from git tracking"
```

**Comment by ace-1331** [comment]
See #1084 for the rework on this PR

**Pull request closed without merging**
