### PR TITLE
New handheld toys: Toothbrushes

### PR DESCRIPTION
**Pull request by Ayesha-678**
Added 2 types of toothbrushes in the handheld toys, and electric one and a normal one.

### CODE REVIEW

**Comment by Ben987** [comment]
This creates a conflict with Dialog_Player.csv, can you review?  Thanks a lot.

**Comment by Ayesha-678** [comment]
Fixed!

**Comment by Ben987** [comment]
Same here, check Dialog_Player.csv

**Comment by Ayesha-678** [comment]
Should be fixed.

**Comment by Ben987** [comment]
You're removing many new lines from Dialog_Player.csv.  Can you double check?  Thanks a lot.

**Comment by Ayesha-678** [comment]
I removed what you told me to remove, I’m not sure what else to do.

**Comment by Ayesha-678** [comment]
Should be fixed now,

**Comment by Ben987** [comment]
Great!  Thanks a lot :)

**Pull request merged**
