### PR TITLE
Improved SleepMask Textures

### PR DESCRIPTION
**Pull request by TheGnarp**
Stumbled across a (probably very old) sleep mask texture that needed a little TLC.
Hope you like the new style that looks a little less like a helmet visor. ^_-

### CODE REVIEW

**Comment by Ayesha-678** [comment]
Yeah, this was the first thing i ever made, so i just got any old image off the internet, i had 0 standards! Thanks for finding a better one~

**Comment by TheGnarp** [comment]
I knew I would step on someones toes with this one, but I'm very relieved that you like it!
Glad you said something, and I was also glad to have your sleep mask in my last role play ^_-

**Comment by Ben987** [comment]
Thanks a lot!  It looks very nice.

**Comment by DMCHiggens** [comment]
i REALLY wish you had just made this a new item. the original was my favorite blindfold in the game and i cant stand this one..

**Comment by DMCHiggens** [comment]
also, it doesnt update color properly. if you go to change its color, it wont do anything. you have to remove it, and apply it with a new color selected.

**Comment by TheGnarp** [comment]
Hey! I already contacted Ayesha about this, since I had no idea who had done the original.
I think it won't be a problem to have both if he agrees.

By the way, I can't change the color of any blindfold when my character is wearing it herself. A applying it to someone else can change the color though.

**Comment by DMCHiggens** [comment]
thats good to know. might be a color system bug then. 
anyway, it seems ben was okay with it, as ayesha's new pr got accepted
this design is okay i just really didnt like how it replaced the old one, especially being so different. >.< 
idk maybe i just really hate change.

**Pull request merged**
