### PR TITLE
Fix/Refactor: Asset description

### PR DESCRIPTION
**Pull request by jomshir98**
Changes how asset description is resolved, preventing the error of names being assigned to different items.

Tested, including translations

### CODE REVIEW

**Comment by Ben987** [comment]
Good idea!  And it doesn't slow down assets loading?

**Comment by jomshir98** [comment]
> Good idea! And it doesn't slow down assets loading?

Yes, it does slow it down. To be exact it takes now 2.3ms instead of 1.4ms to load all assets

**Comment by Ben987** [comment]
@elliesec , @Nina-1474 , with this change, Female3DCG.csv could become quite a mess and the game would still work with it.   Can you think of way we could still keep some structure in there?  Thanks!

**Comment by elliesec** [comment]
I guess there are a few things you could do, but personally I'd say the best way would simply be by checking pull requests that change it. If you really wanted to, it wouldn't be too hard to write a script like the asset check one to check that the entries are suitably grouped, although I don't personally feel that should be necessary.

Other than that you could break the file up into multiple files, or use a more structured format than CSV, but I'd say those would be more trouble than they're worth (not to mention the fact that loading 65 CSV files would be a _much_ bigger performance hit than this change).

**Comment by Ben987** [comment]
Yeah, lets not create multiple CSVs, it will cause more issues and more F5 for players.   And I don't want to run a script each time I pull a new asset change.

Let me know if you find a good solution to keep the CSV in order, we can keep that one on hold until then.

**Comment by jomshir98** [comment]
@Ben987 I can (and planned to do this anyway) write tests in AssetCheck for this

**Comment by Ben987** [comment]
@jomshir98 Awesome!  Let me know when it's ready.

**Comment by jomshir98** [comment]
@Ben987 I've made the checks. Currently it is failing because:
> ERROR No description for asset "ItemHands:SpankingToysLongDuster"
Do you have a name for me to put there?

**Comment by Ben987** [comment]
"Long Duster" is fine for the name.  Thanks!

**Comment by jomshir98** [comment]
@Ben987 Done!

**Comment by Ben987** [comment]
Great!  So how will it work?  We will receive in-game console errors if a description is missing or in the incorrect order?

**Comment by jomshir98** [comment]
> Great! So how will it work? We will receive in-game console errors if a description is missing or in the incorrect order?

No, in game the order doesn't matter at all and there shouldn't be errors in in-game console. If an asset without name somehow makes it in, it will be seen as `MISSING ASSET DESCRIPTION: Group:Name`

The check already happens the same as assetcheck script - putting the cross or checkmark next to the commit, with ability to click on the cross and open details to see error (just like is visible with the "Add check in AssetCheck" commit above, which had error about the Long Duster. Ordering is also checked in the same place

**Comment by Ben987** [comment]
Perfect!  If we can see the missing name or the wrong sort order before committing the pull request it's even better.   Thanks for that one.

**Pull request merged**
