### PR TITLE
Bunny & Cow tail strap variant

### PR DESCRIPTION
**Pull request by ace-1331**
- added a cow&bunny tail strap variant as requested

They were the only one that were only available as plugs

### CODE REVIEW

**Comment by Shiranui-Izayoi** [comment]
Hey wouldn't it be a good idea to add a blank image for the bunny tail? Since otherwise when the game tries to load it when equiped it will fail and create errors right?

**Comment by elliesec** [comment]
> Hey wouldn't it be a good idea to add a blank image for the bunny tail? Since otherwise when the game tries to load it when equiped it will fail and create errors right?

The `Visible: false` flag in the asset definition should prevent the game from trying to render an image for it.

**Comment by Shiranui-Izayoi** [comment]
Ahhh ok then. I wasn't aware that that flag existed. I just saw a lack of image and thought I should mention it.

**Comment by ace-1331** [comment]
Yes, `Visible: false` makes it so no asset at all is looked for when drawing a character so no need for empty images, those items just need a preview

**Comment by Ben987** [comment]
Yes!  That's a good idea.  Cheers!

**Pull request merged**
