### PR TITLE
Greyscaling, color fixes for bondage items & new device images

### PR DESCRIPTION
**Pull request by FeuertinKira**
*greyscaled most bondage items to help with hex color code consistency across items and help with overly bright colors

*adjusted brightness up/down on certain bondage items to help with hex color code consistency across items and too bright or dark colors

*changed chastity bra lock image to a 1x1 pixel image to conserve some space, since previous was just an empty image

*deleted some unused images of Mittens and PawMittens in /ItemArms, since they are now in /ItemHands

*added new image for wooden box

*added new image for water cell

*added new image for milk can

### CODE REVIEW

**Comment by Ben987** [comment]
This is huge!  Have you tested it a lot?  Can you post a few screenshots so we can see the difference?  Thanks a lot.

**Comment by FeuertinKira** [comment]
I have tested them quite a bit, even the just newly added items.

Threw together a little quick comparison on short notice:
Before Greyscaling and color adjusting:
1. https://imgur.com/hCLPway
2. https://imgur.com/6ivWyjk

After Greyscaling and color adjusting:
1. https://imgur.com/5Z9kbsp
2. https://imgur.com/5fP23lj

Bit scuffed since I took the before pictures on the live version in a full room and the after on my test version in an empty one, hence the size difference. But doesnt change much about seeing the results... After greyscaling and adjusting the colors items match generally much better between each other, having the expected color to them. Can even still see the details on nylon rope a bit now despite a brighter color.

For now I've only done the bondage items, maybe I will do some of the worse offending clothing items aswell.

**Comment by FeuertinKira** [comment]
Reverted most of those last changes to keep the pull request clean, sorry about that.

**Comment by Ben987** [comment]
This is tons of work!  Thank you so much, I will test it right now.  Cheers!

**Pull request merged**
