### PR TITLE
Kigurumi Mask

### PR DESCRIPTION
**Pull request by Ada18980**
Adds a mask which covers the head and can be configured to have up to 256 combinations of facial expressions!
The scripts are copied almost entirely from the High Security Straitjacket.

Much thanks to Ellie & Jomshir for help and code, and Miku for giving the the idea :)

### CODE REVIEW

**Comment by elliesec** [comment]
FYI @Ada18980 - I've just raised PR #2031, which once merged should allow you to replace your 256 lock assets with a simple `DrawLocks: false` flag on the asset.

**Comment by Ben987** [comment]
Sure!  Can you try the new property and remove all the blank lock assets?  Thanks!

**Comment by Ada18980** [comment]
@Ben987 Done!

Thanks @elliesec !

**Comment by Ben987** [comment]
Thanks!  I've never seen a mask like that before but I'm sure that players will like it :)

**Pull request merged**
