### PR TITLE
Typo Fixes

### PR DESCRIPTION
**Pull request by klorpa**

### CODE REVIEW

**Comment by Ben987** [comment]
This is great, thanks a lot for checking the typos.  Are you sure about "Colour" instead of "Color"?

I rarely see "Colour".  I'm from North America though, you might be from the UK.  A quick search on google gives a lot more results with Color than Colour.

Thanks!

**Comment by adokilume** [comment]
"Skillfully" is also more common than "skilfully" in American English, according to this: https://grammarist.com/spelling/skilful-skillful/

The rest looks good though.

**Comment by klorpa** [comment]
I assumed the game preferred British spelling over American; there are several pre-existing examples of "colour" for example.

**Comment by Ben987** [comment]
There's no preferred version of English setup, and every developers will write in their preferred version.  Try to use the most popular version I guess, we can use google to start with.  Color has more results than Colour and Skillful has more results than Skilful.  We can go with that.  The rest looks great.  Thanks!

**Comment by Ben987** [comment]
I've merged most of your changes in this commit:
https://github.com/Ben987/Bondage-College/commit/b4fbfbd72e206c432d0f07ed553f42436e125918
Thanks a lot for your help!

**Pull request closed without merging**
