### PR TITLE
Another batch of TS fixes

### PR DESCRIPTION
**Pull request by zorgjbe**
Again, another day, another flurry of TypeScript-related fixes. Most of those are only into comments, there's a few reformats when I saw lines that were too long. The only functional changes are in the last commit (612c941b04fdb28521236e5fe1ae47dd801fc825), where a parameter wasn't being passed down, and a bug in Pandora where we weren't passing the correct thing to `CharacterDelete` (I did quite some runs of that, and hit no issue). The rest should have no effect (unless I missed some code that depends on the RelogChatLog having a name, but I found nothing of the sort).

### CODE REVIEW

**Comment by elliesec** [comment]
Assuming this depends on #3448?

**Comment by zorgjbe** [comment]
Ah, I missed that one. I don't think it needs to, but I'm carrying that one over the other one. I'll fix up the typedef…

**Comment by zorgjbe** [comment]
All done, thanks @elliesec ❤️. I added another one since I noticed another TS error in here

**Review by elliesec — APPROVED** [review]

**Comment by Ben987** [comment]
This one has conflicts, can you resolve them and test again?  Thanks!   I'll try to test all of it this weekend.

**Comment by zorgjbe** [comment]
@Ben Rebased and ready to go. I did take out the reverts I made because of the NPC split PR having been submitted separately, and merged.

**Comment by Ben987** [comment]
Thanks for the quick edit!  Next time, can you split it into multiple pull requests?  It will make it easier for me.  Thanks a lot :)

**Pull request merged**
