### PR TITLE
Hemp Rope Wand Belt

### PR DESCRIPTION
**Pull request by Ayesha-678**
A vibrating wand belt, for the vulva area, made out of hemp rope!

### CODE REVIEW

**Comment by Ben987** [comment]
Thanks!  But check this line:
<script src="Screens/Inventory/ItemVulva/HempRopeBelt//HempRopeBelt.js"></script>

There's an extra " / " in your path.

**Comment by Ayesha-678** [comment]
Oops! I'll fix that!

**Comment by Ayesha-678** [comment]
Fixed!

**Comment by Ben987** [comment]
Great!  I'll test it pretty soon.

**Pull request merged**
