### PR TITLE
Enable selfbondage on rope harnesses

### PR DESCRIPTION
**Pull request by GermanPerson**
In real life it's one of the easiest rigging tasks to tie a harness by yourself.
This commit enables selfbondage with both types of rope harnesses.

### CODE REVIEW

**Comment by Ben987** [comment]
This isn't the rope harness, this is the full arms bondage.  The rope harness can already be done on yourself, check the ItemTorso section.

**Comment by GermanPerson** [comment]
Sorry, I was actually referring to the full arms bondage. I always refer to that as harness too.
My point still stands: a simple rope boxtie that both of the rope options are is trivial to tie by yourself and does not require a great amount of rigging skill.
It should be possible to tie by yourself.

**Comment by adokilume** [comment]
Hope you don't mind if I add a comment here. I don't really have any rigging experience, but I kinda doubt tying your own hands behind your back would be "trivial", without much skill. Maybe it could become possible after you reach a certain bondage skill level, just like in the College game.

**Comment by GermanPerson** [comment]
A nice tutorial I found [here](https://www.boundanna.com/html/en_tech_selfbondageboxtie.html) shows a stripped down version of a boxtie. It uses a small tweak to make it easier, but I think being a  tiny bit inaccurate isn't that bad.

**Comment by GermanPerson** [comment]
Requiring a certain skill would in general be a fun mechanic.

**Comment by Ben987** [comment]
Without lots of knowledge, it's pretty much impossible to tie yourself like that.  Just check the link that you've sent, it's far from simple and you need a metal ring + zip ties.  Someday I might do more complex self bondage but there would have to be a skill requirement.

**Pull request closed without merging**
