### PR TITLE
[Beta fix] [asset] [Natsuki] Plastic roll update

### PR DESCRIPTION
**Pull request by Codefreak64**
A quick resizing of the wrap as it was a tad bit too big, just a visual change that makes it look nicer (and no stray pixels)

### CODE REVIEW

**Comment by Codefreak64** [comment]
image

I cant resolve on my end, I legit cant github wont let me

**Comment by Codefreak64** [comment]
its only an updated image, thats all that this new PR merge is doing.

**Comment by Codefreak64** [comment]
Not exactly sure what I did but thank you Nina for the help on this one

**Comment by Ben987** [comment]
Sure!  Right on time for the next release :)

**Pull request merged**
