### PR TITLE
queue and await AccountUpdate, reduce emit calls

### PR DESCRIPTION
**Pull request by NoneNoname**
only a draft for now since this won't get pulled before the next beta

Example of a user buying items one after another:
image

With this change only a single update is sent to the server:
image

### CODE REVIEW

**Comment by NoneNoname** [comment]
this doesn't require server-side change it only reduces the amount of AccountUpdate messages

**Comment by NoneNoname** [comment]
@Ben987 is this still on hold, if not I will resolve the conflicts

**Comment by Ben987** [comment]
@NoneNoname , I'd like to test it for the next version, the more air we can give to the server the better.  But I've never messed with classes yet so far, so it's kind of tricky for me.  Could you change the PR so it doesn't use classes?  Maybe use a regular function that calls itself every 10 seconds to see if there's something to sync on the account.  Thanks a lot.

**Comment by jomshir98** [comment]
@Ben987 

I would strongly recommend keeping it as a class. Classes are quite simple (if you don't use inheritance, which this doesn't) and very powerful for organising things!

If you already know how to work with objects, classes should take you ~10 minutes to understand. I strongly recommend following site, which will give you everything you need to know.
[https://www.w3schools.com/js/js_classes.asp](https://www.w3schools.com/js/js_classes.asp)

**Comment by NoneNoname** [comment]
we already have classes, none of these prs rise any problems from you, so I don't see why this change should be made at all, and `10 seconds` is a bad idea itself, that is not the same concept with this pr, that will not be a code improvement

pr #2364 `class NotificationEventHandler` accepted by you @Ben987 
pr #1368 `class TextCache`

**Comment by Ben987** [comment]
@elliesec , @Nina-1474 , are you able to support and debug this pull request if we get trouble during the beta?  Anything that touches the client/server communication is always touchy.  Thanks!

**Comment by Ben987** [comment]
It's time to test this one!  Lets hope it will help with the server spikes.  Thanks a lot :)

**Pull request merged**
