### PR TITLE
Messages when plugged or vibrated

### PR DESCRIPTION
**Pull request by Ada18980**
Plays messages occasionally when you kneel/stand up, enter a chat room, use the struggle action, or fail a struggling minigame and exit out. 
These messages appear only to the player and not to others. They add a bit of arousal as well.

### CODE REVIEW

**Comment by Ben987** [comment]
Will there be an option to avoid these messages?  Not everyone will want to output automatic text.  Thanks!

**Comment by Ada18980** [comment]
I'll add an option to the chat settings

**Comment by Ben987** [comment]
Thanks!  Can you also make a preference so players will be able to skip that mechanism if they want to?

**Comment by Ada18980** [comment]
There, I added an immersion setting @Ben987 The messages are still controlled by the sexual activities chat room message, but the actual feature is an immersion option as I plan to expand it later (getting 'distracted' while trying to do things...)

**Comment by Ben987** [comment]
Alright!  I will test it soon.  Thanks :)

**Pull request merged**
