### PR TITLE
Asset: Body Chain Necklace by Titania

### PR DESCRIPTION
**Pull request by elliesec**
## Summary

This PR adds a new Body Chain Necklace item by @QueenTita. Preview below.

image

### CODE REVIEW

**Comment by Ben987** [comment]
This one also creates conflicts.  Thanks again :)

**Comment by elliesec** [comment]
@Ben987 - conflicts resolved.

**Comment by Ben987** [comment]
This one still has one conflict, can you check again?  Cheers :)

**Comment by elliesec** [comment]
A lot of the recent assets we've submitted make changes to the same items, so I expected there to be quite a few conflicts between them. Conflicts have been resolved again.

**Comment by Ben987** [comment]
Thanks again!  I'm curious to try these new items, cheers :)

**Pull request merged**
