### PR TITLE
Id card

### PR DESCRIPTION
**Pull request by Ayesha-678**
An ID card necklace

### CODE REVIEW

**Comment by Ben987** [comment]
Thanks!  I will review it soon, when all my lag fixes are ready.  Cheers :)

**Comment by Ben987** [comment]
That's a good idea.  Should we make it a "nurse" specific item?  Is that why you created it?

**Comment by Ayesha-678** [comment]
Not really. I just made it for any kinda roleplay that benefits from it, so I’d prefer if it wasn’t nurse specific.

**Comment by Ben987** [comment]
Alright!  Lets use the ID Card as a regular item then, thanks!

**Pull request merged**
