### PR TITLE
JSDoc: Typedef + jsconfig.json

### PR DESCRIPTION
**Pull request by NoneNoname**

### CODE REVIEW

**Review by ace-1331 — APPROVED** [review]

**Comment by jomshir98** [comment]
Updated the types to match types checked by `AssetCheck`.
This PR has no functional changes and serves to provide better documentation and help during development.
Later on it will also be possible to automatically detect errors using these types

**Comment by elliesec** [comment]
One small note - as of the recent validation changes, there are now a few instances of `AppearanceBundle`, `AppearanceItem` and `AppearanceBundleItem` that will need updating in `Server.js`, notably on the docs for `ServerAppearanceLoadFromBundle`, `ServerBuildAppearanceDiff` and `ServerBundledItemToAppearanceItem`.

Aside from that, all looks good to me. If there are any other types that got missed out, we can fix them as and when we spot them.

**Review by elliesec — APPROVED** [review]
Happy with this as is (a couple of points mentioned in my previous comment, but they're not essential).

@Ben987 - I'm going to approve this, but won't merge it. I think it's up to you whether it should go in or not, but the change should be a pretty big help to IDE users, and will have no impact on the actual game itself.

**Comment by jomshir98** [comment]
@elliesec I've addressed the points you made

**Comment by Ben987** [comment]
This one has a conflict in Asset.js   Can you resolve it and test again?  Thanks a lot.

**Comment by Ben987** [comment]
Thanks!  I don't use an IDE myself but if it helps you guys and doesn't change the game then it's good for me :)

**Pull request merged**
