### PR TITLE
More kinbaku Club (very Alpha)

### PR DESCRIPTION
**Pull request by wildsj**
Some of chapter 101 in this is very "alpha", don't pull if you are about to update the hosted version. I can disable those sections again if needed.

This PR is to check some changes to the actor.js and drawing.js files, for hiding actor names and a few other functions I need for the club, don't interfere with your own developments.

### CODE REVIEW

**Comment by Ben987** [comment]
Is it ready to merge in the master branch and be included in the next release?  
I'm so curious to try the new version of the club :)

**Comment by wildsj** [comment]
Not really. I could edit the RopeGroup into a neater Alpha version (Currently a lot of loose and dead ends in it.) so that it could all be merged for a Beta testing release of the SlaveTwin section. The players have to go through the RopeGroup section to make one of the twins your slave.

**Comment by Ben987** [comment]
It's fine, no rush :)  Let me know when the version is ready to test and I will try it.  After that we can release a beta version.  This will be tons of fun.

**Comment by Ben987** [comment]
This is great!  I'm very curious to try it :)

**Pull request merged**
