### PR TITLE
[Improvement] [Natsuki] Economy Ballance

### PR DESCRIPTION
**Pull request by Codefreak64**
With all the new assets coming in and the assets we have, one of the biggest problems for new and current players is the ability to get cash fast without spending a lot of time on it.

so I **SLIGHTLY** increased most of the ways to get cash in the club, just to help the money issue thats currently growing

List of changes are below in the commits but i'll put them here as well

```
- Daily Task reward increased from 100 to 120
- Kidnapping clubs base payout increased from 15 to 25
- Maid Minigame reward increased from 10 to 14
- Maid Rescue missions base reward increased from 10 to 15
- Online drink serving base reward increased from 10 to 15
- Asylum treatments base reward for all difficulties increased by 5
- Minimum payout for showing off shop products increased from 5 to 7
```

if there are suggestions for further balancing, please let me know.

### CODE REVIEW

**Comment by Codefreak64** [comment]
had to fix a few dialog options not being changed as well as reverting an accidental nerf

**Comment by Ben987** [comment]
Thanks!  But have you checked with the community to see which job are paying less than others or it's only from your personal experience?

**Comment by Codefreak64** [comment]
it wasn't publically on the discord server, but i did pop into a few rooms in the club and asked around for about a week. these were the end results after about 250 answers to what i asked. did the math on these by doing them for 10 minutes and seeing how effective they were.

taking the info i gotten combined with the whole shop being worth more than 100,000 (and still growing). I figured now would be a good time for a slight buff on some of the money sources

**Review by Ada18980 — APPROVED** [review]
These seem to cover most of the bases.

**Comment by Ben987** [comment]
It's time to test this one!  Thanks a lot :)

**Pull request merged**
