### PR TITLE
Translatable Actor Names

### PR DESCRIPTION
**Pull request by adokilume**
This should take care of issue #110, hopefully without creating any new problems. For now I added CSVs for the languages that were already present in the common folder, though FR and CN are just default English templates and will need to be adjusted.

Everything seemed to be working fine when I tested it in different languages, but please check the code just to make sure I didn't do anything the wong way. For example, I wasn't sure if I should use `CurrentLanguageTag` (which sisn't display any names when I selected a language there wasn't a file for, even though I thought `ReadCSV` would fallback to English in that case) or `GetWorkingLanguage()` (which seems to work better, but will probably change which language it uses depending on wheter the chapter has been translated already - I think that works out well though, so I went with that).

You might notice the line `if (ActorToLoad == "") return;` that I added to `ActorLoad`. I did this because of a strange occurence when talking to the RopeGroup in the KinbakuClub, which added an "empty actor" to the list of Kinbaku Club relationships. It was just a line with stats but no character name, or the "MISSING TEXT FOR TAG" string after my changes. Apparently this is because the script called `ActorLoad` with an empty string to unload the current actor, but instead it created a new actor without a name. I didn't want to change anything in wildsj's code without asking or knowing the reason, so I did this instead. I hope there's nothing wrong with it now.

(Edit: Forgot about Natalie, added her to the list.)

### CODE REVIEW

**Comment by Ben987** [comment]
Awesome!  Have you tested it with all characters to make sure they all show properly?

**Comment by adokilume** [comment]
As of right now, yes.^^ I assumed they'd all work because I copied the main characters' names from the player script (including Sophie, just in case), and I checked the Kinbaku Club before. But yes, I quickly went through all of them again in English and in German and they al seem to work. Unless I forgot someone from the Kinbaku Club, like Natalie at first. But that was mostly because she wasn't in that chapter, so I didn't have her fresh on my mind.

**Comment by adokilume** [comment]
Actually, it seems I spoke too soon, sorry! The names don't show up in Spanish or Russian if you're playing a translated chapter. Probably because GetWorkingLanguage() assumes the files should be there, since the game doesn't actually enter Chapter 999 to fetch the names. Any idea how to fix this? Or would it simply be required for people to translate that file right away when doing a new language?

**Comment by Ben987** [comment]
Correct, chapter 999 isn't translated in all languages.  Could you add something in your code to only use that new part of code if the language is English, French, German or Chinese?

**Comment by adokilume** [comment]
I could, but wouldn't that just create another list of languages that nees to be updated all the time? After thinking about it a bit, maybe a better way to get the same result would be to add an optional parameter to GetWorkingLanguage, so I could pass chapter 999 to it, then it would just default to English as normal. I'd do it in a way so it would still use the current chapter if nothing is passed.

**Comment by Ben987** [comment]
I'm fine with it also.  Just make sure it works with every current languages :)

Thanks!

**Pull request merged**
