### PR TITLE
Massive Expression Expansion and Overhaul

### PR DESCRIPTION
**Pull request by FeuertinKira**
-Added 3 new Blushes

-Reworked every single Expressions Icon

-Removed Eyelids from every single UpperBody image (added helper images for easy and clean removal of eyelids for future UpperBody images)

-Added 13 brand new Eye Expressions, 17 in total counting the old ones

-Added Closed Eyes expression images extracted and reworked from the UpperBody images

-Realigned all eye images for new Left/Top positioning

-Reworked mouth completely, now uses one 'uniform' mouth for all characters with 16 new Expressions

-Realigned all mouth images for new Left/Top positioning

-Old mouths still available for use and functional like before, they just dont show any of the new expressions (I would remove them personally, but I'm sure someone would complain eventually about not being able to use the 5 pixels worth of mouths)

-Added new "Fluids" expression category, featuring 5 drooling expressions, 3 crying/tears expressions and 5 tears+drool combo expressions

-Added new "Emoticon" expression category, featuring various little state icons to display on top of your characters head; examples: bubble that shows afk, bubble that urges people to read a profile description or show little hearts / or an "angry" symbol

-Changed blinking to work by displaying Closed Eye Expression instead of hiding eyes completely (Thank you Atasly for helping out with the coding for this)

-Added drooling on struggling

### CODE REVIEW

**Comment by adokilume** [comment]
I'm currently taking a break from this game and unsure if I'll resume development at a later date at all, so I don't know if my opinion will have much weight. However, just to throw it out there:

I'd like you to strongly reconsider including text labels within the expression icons. I didn't do that for the following reasons:

1. They're not translatable. For people playing in different languages, this is going to feel really strange. If you're gonna have labels at all (which I personally wouldn't want anyway, see my next point), you'd have to either display them another way that's read from translatable text, or add separate images for every single language.

2. They're limiting your imagination. The names I initially gave them in the code were meant for internal reference only. But in practice, these individual expression parts can mean slightly different, nuanced things, depending on how you combine them with others. For example, the "angry" eyebrows look angry if combined with a frowning mouth. But combine them with a smile, and you get the maniacal grin of a mistress who's enjoying herself tormenting her subs, without much anger at all. The reason I turned everything into image icons in the first place was because they were meant to inform the player what they'd look like, and to let them creatively decide what they want to do with that. Rather than dicatate what particular emotion it's supposed to convey.

**Comment by Ben987** [comment]
Wow!  This is huge, thanks a lot.  

Yes, images instead of text would be more intuitive, what we have right now is easy to navigate.  Could you create small icons to select the new expressions?

Does the "Legacy Mouth 1 to 5" show anywhere with these changes?  If so, we need to rename it.

Can you put some pictures of the new drool in game?  I'd like to compare with the one that gatetrek did.  We'll keep the one that players like the most.

Cheers!  Merry Xmas.

**Comment by FeuertinKira** [comment]
I added text to the icons since there is a lot of them now. Before it was okay without, since it is easy and quick to navigate just 2-4 different icons. But there's a lot more now and navigating through up to  currently ~17 icons in some categories and just identifying them at a glance from the image only is not fun. Having both the visuals and the text to identify them by makes navigating to the expression you want to use much faster.

I disagree on it limiting imagination. Nothing is stopping anyone from using "angry" eyebrows in combination with other expression parts to create an emotion that has nothing to do with being angry etc.
If anything there was no imagination to be had beforehand, since there were no expressions to do anything of the sort with in the first place. Maybe it can be changed to display the text through code later on, like it does for the bondage items on the inventory screen.

Admittedly I didnt think of translations, but in all honesty it's also not something I'm very concerned about. The visual representation is still there on each icon and the vast majority of people I've met in game would still be able to understand the words used on the icons.

Legacy Mouth 1-5 show in the wardrobe and you can still select them. Though I fail to see why that needs renaming? Legacy is to refer it as the "old mouths", but sounds a lot cleaner. What else would you want to rename them to? If it were just up to me I would have just removed the old mouths, but I'm sure there's atleast one person out there who would still want to use them, so I kept them in for that circumstance.

I removed gatetrek's drool images from my pull request, since it simply doesn't align with the new mouth shape and expressions. The drooling images I made were made specifically to line up with all the mouth expressions, so it looks decent on -all- of them. There's not much point comparing them with gatetrek's for that reason.

**Comment by adokilume** [comment]
Yes, displaying the labels by code the same way the item names in the inventory are displayed would be much better, both for translatability and editability. In image form, you'd always have to make sure to pick the same exact font etc so it doesn't look weird, which actual text just circumvents. I do feel a little bad for all the work you already put into it to make it this way, this conversation probably should have happened a lot sooner when you had the idea to do that.

Personally, I still believe the labels are more distracting than helpful. If people who don't speak English can tell what the expressions are by the icons, so can the others, probably. And if they're too specific, I do think they might break your immersion for a moment. "Oh, this looks like it could look good for what I want to express, but it's called 'angry', and that's not what I want. Should I still use this?" A picture is worth a thousand words, as they say.

As another example, the "dazed" eye expression probably ended up being used to be seductive or show annoyance more than anything else. I thought it should have a different name from the moment it was added. But I never said or did anything about it because it literally didn't matter, it was just an internal name, never meant to be shown. If that's changed now, I do think it should be renamed to something more generic, like "lidded" or "half-lid". Then again, if all the labels just describe the way the face features objectively look, it's kind of redundant, which once again makes me question if they're necessary.

I'm sorry I'm insisting on this point so much, it's just something I'm kind of passionate about that I feel misses the point of how I intended the exoression menu to be used. Of course it's not really my property, but still. Perhaps the label display should at least be a user preference.

That said, I really do appreciate the work you did. While the extreme blush seems a little over the top for my taste, I've been hoping for someone to add more eye and mouth expressions for a really  long time, and yours look great (from the ones I've seen). So thank you for that.

**Comment by FeuertinKira** [comment]
No, what I meant was even people who dont speak or understand english can use the text to identify the icon quicker.

Still disagree on them being distracting or "breaking immersion", it's entirely subjective. In fact I believe they are neccessary with how many I made. I want to be able to quickly identify the one I am looking for and the text in addition to the icon itself helps a lot with that. I'm always going to be in the camp of the more information is displayed to the player, the better.

Adding the text through coding instead is the only reasonable solution I see here. Although even that one has a few little quirky downsides too. Can't individually fit and position the text on a per icon basis that way. Just one size fits all shrinking of text depending on the length of the word displayed on top of the icon.

**Comment by Ben987** [comment]
@FeuertinKira , can you prepare these screenshots of the new drooling effect in game?  I want to compare it with what we have now.  I'll find a better name than "legacy", no worries there.

**Comment by Ben987** [comment]
@adokilume, you've created the expression system, do you approve all these changes from @FeuertinKira ?  Should we change anything before modifying your work?   

Thanks a lot.  Cheers.

**Comment by Ben987** [comment]
@FeuertinKira , I've chatted with @adokilume and he approves the changes to the expression system, you'll now be both owners of that part of the code.  Only one thing came again, it's the text below the images.  

Can you remove the text from the images?  It will leave more room for people's interpretation and make translators life much easier.  Thanks a lot!

**Comment by FeuertinKira** [comment]
I have responded to that multiple times already aswell. Somehow it's fun to keep repeating the same thing of and over though, apparently.

**Comment by adokilume** [comment]
It's that exact attitude that made me feel like there was no more point discussing this with you any more, you know. Ben asked for my opinion. This is what it is. I could have told you the same thing a long time ago if you had been more communicative and mentioned somewhere what your plans were, and all of this could have been avoided by finding a solution everyone's happy with, before doing any potentially unnecessary work.

**Comment by FeuertinKira** [comment]
What attitude exactly? That I dare to state my own opinion that happens to partially disagree with yours apparently? I find the fact that my points are being ignored at every step a lot more concerning actually.

Also not sure why you're telling me specifically that I need to announce every little thing I'm planning on working on or making for the game in advance. Nobody does this. Did gatetrek announce he was working on some expresison stuff anywhere? Dont think so. Just one example but I can apply to literally anything anyone has made for the game...

**Comment by adokilume** [comment]
I'm not saying you're the only one who doesn't do this, it's a general problem that makes development on this game problematic. As for attitude, I don't mean you aren't allowed to state your opinions. It's just that the way you present them often feels rather provocative and unpleasant. I don't mean to be rude, but it just so happens that my opinion conflicts with yours. That's not a tragedy, it's part of life and happens all the time. All we can do is try to stay as emotionally calm about it as possible and actually talk about it civilly, without implied eyerolling or heated debates. Otherwise this will never be solved, and Ben has the final say as to what happens with his game either way.

**Comment by FeuertinKira** [comment]
You will have to point at where exactly the way I'm presenting my arguments is provocative or unpleasant. I re-read my two responses above that I made to you and I can't find anything where the way I'm stating things is out of line.

**Comment by adokilume** [comment]
It's just a general vibe I'm getting from you, not necessarily just today. There have been times the way you speak just comes across as slightly arrogant. Now, I know I can sometimes get like that too, but I try to keep it to a minimum, because I know it makes talking to me a rather frustrating experience. One recent example that comes to mind was in a screenshot someone showed me in a discussion yesterday, where you facepalmed at someone for stating something inaccurate, even though that person had no way of knowing any better, and generally showing extreme annoyance at people who didn't know every detail about these upcoming changes. Unless they were watching this thread right here, how would they know? Showing some understanding and explaining your point of view in a calm fashion can go a long way, rather than immediately calling out how a comparison of drools is nonsensical, without providing any context for why you think so.
I'm sorry this got so offtopic, by the way. I should have probably opened a little differently, myself. SOmetimes nerves just get the best of us.

**Comment by FeuertinKira** [comment]
Except those responses you are talking about now are coming from a perspective where everything I have been saying has been repeatedly ignored. It is still true that the voting and discussion that Ben put was completely nonsensical. The comparison made little sense and he didnt put any thought into it... I guess how the voting turned out sort of reflects that aswell. Maybe Ben did not understand what my pull request changes or just to "keep everyone happy" even though it made no sense in this particular case.
Considering you "saw a screenshot" as you say, you probably did not see the rest of the discussion. Since if you had you would know that I did explain pretty precisely why things didnt make sense and that there was a lot of information missing.
Besides my "facepalming" was more aimed at the entire discussion happening at all and not at the person assuming something wrongly, since I knew beforehand that was one of the things that were going to happen with that "comparison". So I won't applaud you for taking a screenshot out of context and at face value either...

**Comment by adokilume** [comment]
I did in fact log in with an alt account to take a look at it myself, and indeed saw you explain it later on, but not before a handful more people got annoyed and confused by it. The fact that your facepalm wasn't directed at the person doesn't change that it came across that way, and that a lot of people seemed to perceive you as more annoying than helpful in that discussion.
Sorry for being so direct, but you did ask.

**Comment by FeuertinKira** [comment]
"A lot of people" is extremely subjective and I'd say objectively wrong. Not sure where you are pulling from that I was more "annoying than helpful" either. But regardless it just shows again that discussion was set up badly. I wouldn't have needed to clarify anything if it were setup properly in the first place. If we're assuming that there was a need for it at all.

Maybe you'd understand better if you just 2 weeks working hundreds of new images, several and several new expression. Made them so they all fit together as best as possible and then you're suddenly presented with a supposed vote if we maybe shouldn't rather use these other images instead of the ones you specifically made (and not to offend gatetrek either, but gatetrek said themselves that they did not work very long on the drooling images).
I still dont know what the result of the voting would even be if everyone had voted right instead??
Would we have discarded all the drooling images I made? Only used gatetrek's? But then we'd have new mouths with drool made for old mouths... and would we still had half of my drooling images anyways? Like the ones that are combined with the tear expressions? Or are those discarded too? Like the entire discussion made no sense at all... Voting between "left" or "right" no point at all to it. At most it could have been voting between "left only" or "both"

This is why I'm saying I have been ignored. I kept saying this beforehand. But it seems like nobody, literally nobody, actually read the actual pull request or looked at the files in the pull request.

**Comment by adokilume** [comment]
Well, I did look at the pull request and saw there was text on the icons, which is why I posted my initial suggestion to remove it again.
Once more, and this isn't supposed to be an attack at you specifically: If we had a workflow where planned changes are being discussed before implementation, both issues could have been avoided. You and gate working on the same thing at the same time, as well as you doing all that work of adding text to the icons.

**Comment by Ben987** [comment]
Let's forget all of this.  I'll pull it as it is right now and change the icons myself.  Thanks a lot guys, cheers!

**Comment by FeuertinKira** [comment]
Except I dont agree with no text at all on the icons. 
The idea of not having the text on them comes from a misguided point of view were there are only 3-4 icons in total in each category, not up to 17 or 18...
I was actually working on replacing the text on the icons itself with a code base display instead.

**Comment by FeuertinKira** [comment]
"Always respect other contributors work, it's very important." But mine doesnt need to be respected?

**Comment by FeuertinKira** [comment]
This makes me think too. Instead of doing a pointless vote about the drool, why is there no voting about text or no text on the icons? @Ben987

**Comment by adokilume** [comment]
Please keep in mind that Ben owns this game, not any of us, no matter how much content we add to it. While the work you do is definitely being appreciated (even by me, since I've been hoping for someone to add more eye and mouth expressions for months, as I said before), I can't say the same about your insistance over this aspect of it. It's up to Ben to ultimately decide what happens to his game and what gets added to it. All we can do is provide our own solutions and advice, but we can't force any of it. It's not like everything always went the way I would have done or preferred it either, and you'll certainly find examples of me expressing my discontent over things in the past. But in the end, it's not up to me, so all I can do is accept these decisions and move on with my life. This time happened to work out differently.
As for your point of view of icons needing text if there's so many of them; I think the much more elegant solution for this would be to just make the icons more distinct. Some of them might need some tweaks in the future anyway, and I've definitely seen some character builders before that manage to have a similar amount of choices with recognizable icons (especially Japanese games). If you're saying non-English speakers would be able to recognize and memorize the words by the way they look (and some of them were so squeezed that they were barely legible anyway), the same is certainly true for icons that look distinct enough, and the sequence they appear in.

**Pull request merged**
