### PR TITLE
Seamless Catsuit

### PR DESCRIPTION
**Pull request by Kitsune-hellfire**
Seamless catsuit, alteration of orginal just with no zippers on this one, left the price as the same as catsuit

if these are added please credit them under my Club name "Kirsty"

### CODE REVIEW

**Comment by Ben987** [comment]
Awesome!  It creates conflicts with the latest pull requests though, can you check them out?

Also, why are you adding a comma on these lines of the catsuit: 
{ Name: "Zip", AllowColorize: false },

Since the array ends, there should not be an extra comma there.

Thanks!

**Comment by Kitsune-hellfire** [comment]
okay, think that fixed it, as for the comma, must have been a typo on my side, sorry for that

**Comment by Ben987** [comment]
There's still an extra comma on line 218 and 220.  Can you check these?  Thanks.

**Comment by Kitsune-hellfire** [comment]
should be sorted now

**Comment by Ben987** [comment]
The extra comma is still there but I'll remove it in another commit.  Thanks a lot!

**Pull request merged**
