### PR TITLE
Enhanced Color Picker (BUGFIX)

### PR DESCRIPTION
**Pull request by vsanvsan**
Original Feature PR: https://github.com/Ben987/Bondage-College/pull/598
Bug Report PR: https://github.com/Ben987/Bondage-College/pull/619

Also fixed a bug which color picker won't work on single click/touch event without move the mouse/finger

### CODE REVIEW

**Comment by vsanvsan** [comment]
BUG: player cannot input colors to input element

waiting to be fixed

**Comment by NoneNoname** [comment]
I think the event listener for the start should only be active if the color picker is drawn and not constantly, so instead of the window load event it could be added when the color picker is selected to be active and removed on exit

**Comment by vsanvsan** [comment]
> I think the event listener for the start should only be active if the color picker is drawn and not constantly, so instead of the window load event it could be added when the color picker is selected to be active and removed on exit

True, that'll be more elegant.

**Comment by Ben987** [comment]
Thanks!  I'll test it right now.  Cheers :)

**Pull request merged**
