### PR TITLE
Replace the beatmap, adding extra details, add description and instructions

### PR DESCRIPTION
**Pull request by sevensonix**

### CODE REVIEW

**Comment by Ben987** [comment]
It looks great!  I'll try it right now.  Thanks :)

**Comment by adokilume** [comment]
@sevensonix Could you extract the text strings that are displayed during the rhythm game into a CSV file? Otherwise they aren't translatable.

**Comment by sevensonix** [comment]
> @sevensonix Could you extract the text strings that are displayed during the rhythm game into a CSV file? Otherwise they aren't translatable.

Yes I can, but I don't know how the translation mechanism work so far. I'll looking into that once I finished new charts for the game. If the translation issue is urgent and I'll make it prior to what I'm currently doing.

**Comment by adokilume** [comment]
It's not really a big deal, I'm currently finishing the German translation for all the new stuff since the last version, but this game doesn't have that much text, so it can wait until next time.

**Pull request merged**
