### PR TITLE
20+ new Items, fixes & adjustments

### PR DESCRIPTION
**Pull request by FeuertinKira**
-Added new Micro Bikini

-Added new One Piece Swimsuit

-Added new Sexy Beach Bra

-Added new Sexy Beach Panties

-Added new Micro Bikini Top

-Added new Heavy Weight Clamp

-Added new Nipple Weight Clamp

-Added new High Security Vulva Shield

-Added new Butt Plug Lock

-Added new Steel Chastity Panties

-Added new HarnessPanties1, lockable variant of existing regular panties

-Added new HarnessBra1, lockable variant of existing regular bra

-Added new HarnessBra2, lockable variant of existing regular bra

-Added new Corset3, lockable variant of existing regular bra

-Added new Corset4, lockable variant of existing regular bra

-Added new Corset5, lockable variant of existing regular bra

-Added new Nipple Gems Piercings

-Added new Nipple Chastity Guard Shield

-Added new Nipple Chastity Cross Shield

-Added new Strict Posture Collar

-Added new Noble Corset Collar

-Added new Heart Collar

-Added new Latex Posture Collar

-Added new Latex Blindfold

-Added more functionality to HeadphoneEarPlugs, allowing them to change deafen settings to simulate them being turned on/off and adjusted volume

-Added extra layer for DuctTape on arms, covering the complete upper body, now including the shoulders

-Adjusted all ItemCollar images to fit the new Left/Top position, this was neccessary to accomodate the new bigger collars

-Added extra functionality to the RoundPiercing and WeightedPiercing for ItemNipplesPiercings, allowing for a chain running from them to the collar to be attached

-Added new Sleek Leather Chastity Belt

-Changed ItemPelvis items to support body sizes directly, adding all the images for the old belts, was neccessary for new items I added since they needed to scale with body sizes

-Changed Full Mummy for DuctTape on ItemHead to hide all hair

-Fixed a spelling mistake in Dialog_Online.csv, expresso should be spelled espresso

-Added ItemHide entries to fitting items, to prevent odd visuals with the new chain connecting RoundPiercing and Weighted Piercing to the characters collar

-Moved NeckCorsetGag to ItemNeck, renamed LeatherCorsetCollar

### CODE REVIEW

**Comment by Nythaleath** [comment]
Question, why did you change the leather chastity belt image without asking first? I would've appreciated a heads up

**Comment by FeuertinKira** [comment]
Meh, cause you said in the past, if someone can improve the images, that it'd be fine. If it's not wanted though I will just add it as a seperate new item instead.

**Comment by Nythaleath** [comment]
thank you for adding it back and Yes i did say that and i still mean it, if you want to IMPROVE the image go right ahead, but replacing it is compeletly different.

**Comment by FeuertinKira** [comment]
It's ... not different at all. I purposefully used an image that looks similar to the LeatherChastityBelt. But it's whatever now.

**Comment by gatetrek** [comment]
made sure got all the images >/w/< normally u miss or two in your big upload

**Comment by FeuertinKira** [comment]
@gatetrek Whats that comment for? I always check through multiple times before I make pull requests. Doesnt mean I can't still overlook something, but unless you found something thats missing or whatever you're implying (and then decided to not mention what it is)... then it's just a jackass comment. Sorry.

**Comment by wildsj** [comment]
I just tried the locking butt plug. It is set to Block: ["ItemButt"], blocking itself so once fitted it cannot be accessed to ever remove it or even fit a padlock to.

Also someone suggested adding a device just like that to me in the club a few days ago, with the option to attach a chain to it like collars can have to secure a slave.  As you have added this plug now, I pass that suggestion on to you.

**Comment by FeuertinKira** [comment]
Fixed the error with the Butt Plug Lock on my end. Thanks for letting me know. And about the suggestion, you mean like a chain running from the plug to the floor, like the existing long and short chain?

**Comment by Nythaleath** [comment]
just want to point out the butt plug lock has a name its called a pear of anguish or choke pear

**Comment by wildsj** [comment]
Yes, acting like the long and short chains do on the collars, but on the butt plug. They also asked about a chain or rope for attaching the anal hook up to the ceiling, to have the same effect.

**Comment by Ben987** [comment]
Some conflicts were created with all the stuff that was merged.  Can you validate with the latest version and sort the conflicts?  Thanks a lot.  Cheers.

**Comment by Ben987** [comment]
Wow!  This is huge!  Thanks a lot for all of this, I'll try it later today.

**Pull request merged**
