### PR TITLE
Fixes for the Strait Dress and Removal of redundent ItemHides.

### PR DESCRIPTION
**Pull request by Shiranui-Izayoi**
Removed the HideItems from the MermaidSuit since all of them were ItemFeet which is already hidden via the normal Hide.

Added "LegsClosed" to any item that has "StraitDressOpen". Since there doesn't seem to be a reason not to and it will better respect functions looking for "LegsClosed" which "StraitDressOpen" is very similar to. If there is a reason not to then feel free to revert this the effect items are as follow. StraitDressOpen, SeamlessStraitDressOpen, Bitchsuit, BitchSuitExposed & MermaidSuit.

Removed "ItemFeetMermaidRopeTie" since the item no longer exists in game due to being merged with HempRope thus the hide is no longer needed.

### CODE REVIEW

**Comment by Ben987** [comment]
This pull request creates a conflict with another fix to the strait dress.  Can you review please?  Thanks a lot.

**Comment by Shiranui-Izayoi** [comment]
I assume you mean the fix for the ornate cuffs sure I can fix that. If I remember correctly I will only need to add in ItemFeetOrnateAnkleCuffs to the dress. I was thinking of including that but Ace said he already was. I will update the request soon.

**Comment by Shiranui-Izayoi** [comment]
There I think that should fix the conflict if not I will update it again.

**Comment by Ben987** [comment]
There are still 6 conflicts left in your pull request.  Can you review them?  Thanks a lot.

**Comment by Shiranui-Izayoi** [comment]
Ok hopefully that should fix it. I really should have just made those changes myself in the commit instead of removing them when I heard Ace was working on it.

**Comment by Ben987** [comment]
Awesome!  Everything seems to work now.  I will add it to the next beta.  Cheers :)

**Pull request merged**
