### PR TITLE
SetPose -> SetType bugfix only

### PR DESCRIPTION
**Pull request by NoneNoname**
I extracted the bugfix part from the other commit

### CODE REVIEW

**Comment by Ben987** [comment]
Should you leave the NULL validations?  It could lead to code crashes if you remove it.

**Comment by Ben987** [comment]
And what does this fix exactly?  What bug is there in the current version that I can recreate and validate?

**Comment by NoneNoname** [comment]
in the modified DuctTape.js the Item.Property use Type in the code while the UI use Restrain which do not work

**Comment by Ben987** [comment]
What doesn't work?  Can I see the bug now if I play?  Will I get an error message?  I want to make sure it actually fixes the bug.

**Comment by NoneNoname** [comment]
other pull request fixes the same thing (Asset Type Info)

**Pull request closed without merging**
