### PR TITLE
Refactor: Bunny tail vibe to extended vibrator

### PR DESCRIPTION
**Pull request by SandrineBC**
# Summary
Refactors the vibrating bunny tail to the extended vibrator script

### CODE REVIEW

**Review by elliesec — APPROVED** [review]
Looks good to me.

**Comment by Ben987** [comment]
This one creates a conflict.  Can you resolve it and test again?  Thanks!

**Comment by Ben987** [comment]
Is this one really ready for review?  There are 1153 files changed.  Thanks!

**Comment by jomshir98** [comment]
> Is this one really ready for review? There are 1153 files changed. Thanks!

Actually, this is GitHub f-ing up for some reason. Comparing locally only `BunnyTailVibePlug.js` and `Female3DCG.js` are changed.

@SandrineBC I would recommend either editing PR and changing the base branch before changing back or closing this one and creating new one; this *should* fix this issue

**Comment by elliesec** [comment]
I've updated the base branch to master - that should have cleared up the excess files.

**Comment by Ben987** [comment]
Great!  Thanks a lot everyone :)

**Pull request merged**
