### PR TITLE
Emergancy Fix for the face paint 

### PR DESCRIPTION
**Pull request by Shiranui-Izayoi**
Not sure how I didn't catch it or how it wasn't caught anywhere else, but I had missed that the face paints added weren't in the right position for the assets and thus were floating around the face area. I have fixed this and it should be merged before the beta.

Ok sorry because of said forgetting to update before fixing it considered everything new. So had to pull it down and stick it back up.

### CODE REVIEW

**Review by ace-1331 — DISMISSED** [review]
for reference, you can just push on the same branch, no need to re-do a PR when you push more commits on the same branch. (your previous PR was fine after you merged)

**Comment by Shiranui-Izayoi** [comment]
> 
> 
> for reference, you can just push on the same branch, no need to re-do a PR when you push more commits on the same branch. (your previous PR was fine after you merged)

Yes I am aware that I can repush on the same branch I have done so a lot. Just when I pushed on that branch when I reloaded it it was showing that things that had already been uploaded were being reuploaded as well as other such things. Mayb have just been a bug on my end but I didn't think so at the time so I closed and reopenned as it looks like it glitched out for me.

My bad shouldn't happen again.

**Review by ace-1331 — CHANGES_REQUESTED** [review]
you're pushing 7 extra unused assets that were removed in a previous PR (the ClothAccessory version doesnt need assets in Poses like AllFours, etc.)

**Comment by Shiranui-Izayoi** [comment]
> 
> 
> you're pushing 7 extra unused assets that were removed in a previous PR (the ClothAccessory version doesnt need assets in Poses like AllFours, etc.)

Fixed

**Review by ace-1331 — APPROVED** [review]

**Review by Ayesha-678 — APPROVED** [review]

**Pull request merged**
