### PR TITLE
Added deafening effect to hood, number 2.

### PR DESCRIPTION
**Pull request by GermanPerson**
I now use the standard speech garble functions, although I had to create a function combining both.
I didn't feel confident to modify the normal SpeechGarble() functions since a lot of stuff seems to depend on them.

What do you think?

### CODE REVIEW

**Comment by Ben987** [comment]
That's good.  But there must be a way we can re-use the standard garble functions isn't it?  So we don't duplicate the code.  Also, the deaf effect should be applied when NPC speaks to the player.

**Comment by GermanPerson** [comment]
I didn't spot a function that easily handles all text displayed. One way to
do that would be applying a gag effect to all NPCs when the players ears
are plugged, but that's a pretty ugly hack.
Do you have any suggestions?

Ben987 <notifications@github.com> schrieb am Mi., 31. Juli 2019, 23:14:

**Comment by GermanPerson** [comment]
Okay, I found a way that worked and removed all duplicate code.
Please review.

**Comment by Ben987** [comment]
That looks good, have you tested it with NPCs?  Does the dialog boxes/flow still works fine?  Thanks

**Comment by GermanPerson** [comment]
I tested it with a few NPCs I could find and didn't spot any issues.
However, I don't know where to find all them, so it might be a good idea if
someone more familiar with the game tests this further.

Ben987 <notifications@github.com> schrieb am Fr., 2. Aug. 2019, 00:08:

**Comment by Ben987** [comment]
Alright!  I'll merge and test it a little later, thanks a lot, cheers :)

**Pull request merged**
