### PR TITLE
Changed behavior of Emote Messages

### PR DESCRIPTION
**Pull request by SandrineBC**
Small change of the 'Emotes' behavior.
If the first character after the * is a "'" or a "," no blank is added in the message.
So that "*'tail swishes" now is displayed as "Sandrine's tail swishes" instead of "Sandrine_'s tail swishes"

### CODE REVIEW

**Comment by Ben987** [comment]
Thanks, but why are you also pushing changes to Female3DCG.js ?

**Comment by SandrineBC** [comment]
Because I’m an idiot?
Honestly, I don’t know. Please ignore that.

**Comment by Ben987** [comment]
This creates a conflict for Female3DCG.js, can you only push the required code?  Thanks a lot.

**Comment by ace-1331** [comment]
@SandrineBC For reference, it looks like you're missing PR #896 (updating your pr by merging that branch into this one should fix it)

**Comment by Ben987** [comment]
PR #896 is already merged in the master branch.  Maybe it's not in your branch though.  Just make sure you only push code that's required for your PR.

**Comment by SandrineBC** [comment]
Then reject my PR please. I’ll do it again, when I’m back online. Sorry for your inconvenience.

**Comment by Ben987** [comment]
Sure, just create a new one when you're ready :)

**Pull request closed without merging**
