### PR TITLE
New item: Pig nose

### PR DESCRIPTION
**Pull request by ace-1331**
all credit to Titania for the assets, I just did the code

### CODE REVIEW

**Review by Ada18980 — CHANGES_REQUESTED** [review]
I think the straps ought to be removed from the nose, can present visual weirdness otherwise like a slightly pink outline on the straps.

**Comment by Ada18980** [comment]
Oh, didnt realize requesting changes blocked merging O.o

**Review by Ada18980 — APPROVED** [review]

**Comment by QueenTita** [comment]
So do I work on removing the straps or its not necessary?

**Comment by Ben987** [comment]
That's a fun idea.  Thanks a lot you two :)

**Pull request merged**
