### PR TITLE
Refactor: Removes duplicated assets for `ItemMouth2` and `ItemMouth3`

### PR DESCRIPTION
**Pull request by elliesec**
## Summary

This is a follow-up to #2388, and uses `DynamicGroupName` to remove all assets in the `ItemMouth2` and `ItemMouth3` groups which were duplicating assets in `ItemMouth`. It also adds a missing `Audio` entry for the rope gag in `ItemMouth3` that I noticed whilst testing.

I've manually tested all affected items to ensure that they all behave exactly as they did before.

### CODE REVIEW

**Comment by Nina-1474** [comment]
You could set DynamicGroupName at group-level for ItemMouth2 to simplify it. 
And I'd argue that the two muzzles that are only in ItemMouth3 should be included in lower mouth slots blocking the higher ones, giving the same effective functionality and allowing the same change for ItemMouth3.

**Comment by elliesec** [comment]
> You could set DynamicGroupName at group-level for ItemMouth2 to simplify it.
> And I'd argue that the two muzzles that are only in ItemMouth3 should be included in lower mouth slots blocking the higher ones, giving the same effective functionality and allowing the same change for ItemMouth3.

I absolutely could move `DynamicGroupName` up to the group level - and that was actually something that I'd planned for a subsequent pull request. I don't disagree about the muzzles either, but this PR was purely about deleting things - I wasn't intending on changing anything.

**Comment by elliesec** [comment]
I've moved `DynamicGroupName` up to group level for both `ItemMouth2` and `ItemMouth3`, but have not moved the two muzzles as I'd rather not increase the scope of this PR beyond `Female3DCG.js`. I'll make that change in a follow-up PR.

**Comment by Ben987** [comment]
This one creates a conflict with another pull request.  Can you double-check?  Thanks :)

**Comment by elliesec** [comment]
Conflicts have been resolved.

**Comment by Ben987** [comment]
That's a big cleanup, I love it.  Thanks a lot :)

**Pull request merged**
