### PR TITLE
Three New Items & Small Adjustments

### PR DESCRIPTION
**Pull request by FeuertinKira**
-Added new Inflatable Vibrating Butt Plug, the equivalent of the Inflatable Vibrating Dildo, just for the backside!

-reordered entries in Dialog_Player.csv very slightly to make it a bit easier to keep overview

----------------------------------------------------
-Added new Polished Mittens

-----------------------------------------------------
-Added new Sexy Bikini

-Changed priority for SuspenderTop;   initially put it lower in the hopes of creating some interesting clothing combos, but it looked odd with most bras, so I moved it up

-Changed Hidden Socks on LatexPants to be more nuanced;   no need to hide all of them, when some of them actually look great in combo

### CODE REVIEW

**Comment by Ben987** [comment]
Awesome!  I'll prepare a second beta with all of that soon.

**Comment by adokilume** [comment]
I know this was already merged, but I just wanted point out that in Dialog_Player.csv, the four lines meant for inflating the plug have the word "dildo" in them, rather than butt plug. Noticed this while translating. Is it okay if I correct those lines in my next translation Pull Request? Would probably result in less back-and-forth.^^'

**Comment by Ben987** [comment]
Sure, if you see mistakes like that, go ahead and correct them.  Thanks.

**Comment by FeuertinKira** [comment]
Already have a pull requst up that fixes this

**Comment by adokilume** [comment]
Yep, I saw that one, and added my translation pull request with the lines already adjusted to match. :)

**Pull request merged**
