### PR TITLE
Lock for cross

### PR DESCRIPTION
**Pull request by Uwnodi**

### CODE REVIEW

**Comment by Nina-1474** [comment]
The item itself is still in the image rather than having the locks only.

**Comment by Ben987** [comment]
Thanks, but it now creates a conflict with other pull requests, can you validate?  Also, have you made sure that the cross creator intended the item to have locks?  @Nythaleath , do you want to add a lock to the cross?  Thanks!

**Comment by Nythaleath** [comment]
Yeah this is fine I did intend on making it lockable and as far as im aware Sybil was working on making custom lock assets as she is the one that made the cross asset in the frist place, so this should be fine for now and then when she finishes she can replace the lock asset with her custom one

**Comment by Ben987** [comment]
Awesome!  Thanks you two :)

**Pull request merged**
