### PR TITLE
Shock command for the futuristic vibrator

### PR DESCRIPTION
**Pull request by Leilatwentytwo**
Adds the ability to trigger a shock with the voice activated futuristic vibrator.

### CODE REVIEW

**Comment by Ada18980** [comment]
Looks good :)

**Comment by Leilatwentytwo** [comment]
> Looks good :)
> 
> Have you checked the UI to make sure the button doesn't come off the edge of the screen?

Yeah, the UI seems to be fine.  Though, it occurs to me I have no idea how it would show up on mobile.

**Comment by elliesec** [comment]
> Great! Yeah, the UI seems to be fine. Though, it occurs to me I have no idea how it would show up on mobile.

That won't be an issue. The game maintains a 2:1 aspect ratio regardless of screen size/orientation. It just scales down until it fits inside the available area.

**Comment by Ben987** [comment]
Awesome!  Thanks for that one :)

**Pull request merged**
