### PR TITLE
Fix suspension and hemp rope to allow kneeling spread when appropriate

### PR DESCRIPTION
**Pull request by zorgjbe**
This changes the ceiling rope and chain to allow kneeling and spreading when suspended (legs wiggling's a thing now), the KneelingHogtie as well, and fixes the leg zipties preventing someone from kneeling.

### CODE REVIEW

**Comment by Ayesha-678** [comment]
The purpose of the ceiling rope is to NOT allow kneeling

**Comment by zorgjbe** [comment]
…right, I was trying to enable it when raised only, but yeah, that make sense. I'll try to make it do that.

**Comment by zorgjbe** [comment]
Here, that works correctly now, no more kneeling while still touching the ground.

**Comment by Ben987** [comment]
Thanks a lot!  I'm curious to test this one :)

**Pull request merged**
