### PR TITLE
Longer Bio & Chat Messages

### PR DESCRIPTION
**Pull request by Shiranui-Izayoi**
Lengthened the Chat Messages to 1000 characters so 4 times the original length because honestly 250 is way to short for more detailed RP.

Lengthed the max length of Bios to 10,000 characters as it is crazy hard to explain yourself in 1000 characters.  While most likely won't use it, it is nice for those that do.

If there is a reason that it is limited like this then please let me know. But to my knowledge there is no reason for it to be like this. Since it only hurts those that want to go into more detail. Like myself.

### CODE REVIEW

**Comment by jimmyG1** [comment]
i am so with this there is so much to my charaters and i cant put all of the info i wunt becuse of how limdid i am

**Comment by Ben987** [comment]
A longer bio is on my list also, but to save space on the server we should compress the data.  Have you seen the LZString library?  It can compress string data.  Try to use it in your pull request and having 10000 characters will be no issue.  Thanks!

**Comment by Shiranui-Izayoi** [comment]
> 
> 
> A longer bio is on my list also, but to save space on the server we should compress the data. Have you seen the LZString library? It can compress string data. Try to use it in your pull request and having 10000 characters will be no issue. Thanks!

I have actually not heard about that library and I currently have no idea how to use or implement it. I will look into it, but I can't promise anything.

**Comment by jomshir98** [comment]
> I have actually not heard about that library and I currently have no idea how to use or implement it. I will look into it, but I can't promise anything.

@Shiranui-Izayoi I've worked with that library a lot in the past. If you wouldn't mind, I can create my own PR with these changes and compression on top of it.

**Comment by Shiranui-Izayoi** [comment]
> 
> 
> > I have actually not heard about that library and I currently have no idea how to use or implement it. I will look into it, but I can't promise anything.
> 
> @Shiranui-Izayoi I've worked with that library a lot in the past. If you wouldn't mind, I can create my own PR with these changes and compression on top of it.

Sure go ahead I haven't managed to make any headway with it so far. Just mention somewhere in the description that the inital idea for expanding the bio and chat lengths was mine and we are all good. To be fair though it isn't like I am the first to think up this idea. If you want to contact me on Discord my Discord is Alastair#3955

**Comment by jomshir98** [comment]
Done with compression in #1967 . Please check it and close this one, if you are happy with it @Shiranui-Izayoi

**Pull request closed without merging**
