### PR TITLE
Enhanced chat search

### PR DESCRIPTION
**Pull request by Ada18980**
The room filter now searches through descriptions as well as titles. So if someone has 'rp' in their room description but not their title, their room will still show up in the search.

### CODE REVIEW

**Comment by Ben987** [comment]
Instead of doing two calls on the client side?  Should we do one call and modify how the server returns the result?  Cheers!

**Comment by TessaTech** [comment]
Correct me if i'm frong, but the way i understand it you do two queries. One without search phrase and one with. Then you use the full result to filter for descriptions on client side and join them with the server's name filter results.

**Comment by NoneNoname** [comment]
the only reason for the server to get the search, in this case, is to add the private room which may exist and wouldn't be added otherwise

so we want the server to have minimal effort to complete the query just do not check against include in Name nor Description, just add a room if it private and have the exact name as the query, and always add all rooms, and let the client filter, sort however it wants it

**Comment by TessaTech** [comment]
It depends if we want to cut the calculation power or bandwidth. Calculating things on the server might result in a higher cpu usage for the filtering but reduces the transaction's load since only the filtered room names are transmitted.
Always sending all room names increases the packet size but saves some CPU ressources in return.

Since filtering happens on server side anyways right now, the removal of that from the server would require a server change anyways. If we leave the server like this and let the client handle filtering now, we'll only get higher packet sizes without performance gain for the server.

**Comment by Ada18980** [comment]
My main justification for the double query is that there are a lot of server changes lately and I don't want to add additional complicating factors. But it should be a simple change on the serverside as well.

**Pull request closed without merging**
