### PR TITLE
Feature: Hand restraints add to difficulty when removing other items

### PR DESCRIPTION
**Pull request by SandrineBC**
# Summary
As of now, it's irrelevant wether the hands of a player are restrained, e.g. by mittens or tape, when they try to struggle out of some bindings. This PR changes this and adds half the difficulty (rounded up) of the player's hand restraints to the struggle challenge.
This resolves issue [#878284](http://www.hostedredmine.com/issues/878284)
# Details
## What it does
Changes occur in two files 
**`Character.js`**
* Adding the functions `GetClumsiness` that returns either 0 (if the player's hands are not restrained) or half (rounded up) of the player's hand restraint base difficulty
**`Dialog.js`**
* Changed the function `DialogProgressStart` so that the clumsiness of the player is taken into account when the challenge level is calculated
* Excluded hand restraints from this difficulty change
## Testing
* Tested that feature on my own server by letting a character struggle out of a restraint and comparing that challenge level with the one after a hand restraint was added
* Tested with the following restraints
    * Paw mittens
    * Padded mittens
    * Leather mittens
    * Padded leather mittens
    * Duct tape
    * Polished steel mittens

### CODE REVIEW

**Comment by SandrineBC** [comment]
Excluded the hand restraints themselves from the added difficulty, which makes sense. Thanks for the hint, @Ben987

**Comment by Ben987** [comment]
Check this change I've did a few days ago: https://github.com/Ben987/Bondage-College/commit/7a115643501776917eac61dc1494d4a1c26f235d

It adds to difficulty for the hands (4) + arms (4) + mouth (2) combo.  Let me know if you like it of if we could add more to it.

**Comment by SandrineBC** [comment]
Hi Ben,
here are my 2 cents
* I like the idea to incorporate the arms and mouth slot to added difficulty 
* I think it's a great idea to outsource the difficulty change to a function in `Character.js` so other contributors could use it as well. Afaik @elliesec wanted to work on a kind of manipulation screen for the combo locks, where an outsourced function could come in handy (see [Ticket #879454](http://www.hostedredmine.com/issues/879454))
* Instead of using a constant modifier, you could take the item difficulty into account as well. So it becomes herder to struggle with polished steel mittens than with padded paw mittens
Cheers,
Sandrine

**Comment by elliesec** [comment]
Hi @Ben987 ,

I think 7a115643501776917eac61dc1494d4a1c26f235d is a good start for something like this. Like Sandrine said, I think abstracting that functionality for hand items into a function on characters would open up the possibility of it being used in other places (as Sandrine said, I had some intentions on enhancing the combination lock screen to incorporate mittens/blindfold-specific functionality - see [879454](http://www.hostedredmine.com/issues/879454) for details).

Allowing for a more open-ended scale of "clumsiness" would also open up some possibilities on that front I think as well, even if in the struggle code hand items add a flat +4. That could still be implemented as below, while allowing a more fine-grained scale to be used elsewhere.

```js
if ((PrevItem.Asset.Group.Name != "ItemHands") && (C.GetClumsiness() > 0)) S = S - 4;
```

**Pull request closed without merging**
