### PR TITLE
VR headset

### PR DESCRIPTION
**Pull request by Ada18980**
Adds a VR headset into the game with options to either not blind, display a black screen, or show a custom background. Also adds the new custom background, and features to allow any blindfold or hood to have this kind of effect.

### CODE REVIEW

**Comment by Ada18980** [comment]
The asset check fails because I added a new asset type. Is this expected, @jomshir98 ?

**Comment by Nina-1474** [comment]
You need to add the new asset property into \Tools\Node\AssetCheck_Types.js.

**Comment by Ada18980** [comment]
> You need to add the new asset property into \Tools\Node\AssetCheck_Types.js.

Thanks!

**Comment by Ben987** [comment]
Sure!  That's a fun idea.  Too bad we have to hardcode the room names in Drawing.js but we can always find a better solution later.  Thanks!

**Pull request merged**
