### PR TITLE
Chinese (Simplified) translation - C999 (Only items), C000, C001

### PR DESCRIPTION
**Pull request by Dwscdv3-R18**
Whoa, what a huge project... I took about 7 hours for only C000 and C001 fully translated.

My skill isn't that advanced though... Feel free to PR or tell me if anyone found a mistake.  
But maybe I can't reply in time, because this is a dedicated sub account for R-18 related stuff, so I won't log in frequently. Email me if it is urgent.

---

I made some notes inside `_Translation/CN` directory, it includes:
* Manifest (English) **<-- important**
* Glossary table (Chinese) - *for a consistent translation style*
* To be discussed list (English) - *something that I can't figure out how to translate*

---

The last thing, there is a patch included. I changed the way to choose the language for CSV files.  
I don't know should I make these change, this is your -- the developers' -- choice. If you dislike it just submit a commit to revert these changes.

Before of this, there was a hardcoded translation progress, if the current chapter is marked as translated, then it loads the translated version, otherwise English version.  
Now it directly request the translated version, if it returned status code 404 (Not found), then fallback to the English version, though it may slow down the load time on not yet translated scenes.

Also I refactored the `ReadCSV` function and its every calls to make it easier to use (mainly for that fallback), but don't worry, I kept the backward compatibility with the old usage.

---

Btw, is there an designer for these CSV files? Or I have to edit them using text editor or Excel?

Love this game ;)
~~especially the submissive branches~~

### CODE REVIEW

**Comment by Dwscdv3-R18** [comment]
Um... I commited these from my main account... (facepalm

**Comment by Dwscdv3-R18** [comment]
Excuse me,  
I have a question about the "loose" state in almost every gear's action.  
What does it mean? "Not that tight" or "Not in use and you're now in restraint" or anything else?

**Comment by 921574531** [comment]
哈喽，你能把全部内容汉化吗，本人英文渣，没有那个实力。非常感谢！

**Comment by Ben987** [comment]
Hello, sorry I don't understand Chinese.
Is this a translation to add somewhere in the game?

**Comment by 921574531** [comment]
I could try.

**Comment by Ben987** [comment]
Alright!  Let me know if you need help :)

**Comment by 921574531** [comment]
Can you send me the full contents of the second chapter? This is convenient for me to translate, the best is email to me, I am not too good at operating that website

**Comment by Dwscdv3-R18** [comment]
> 哈喽，你能把全部内容汉化吗，本人英文渣，没有那个实力。非常感谢！

抱歉我最近比较忙，翻译工作可能会在十二月或明年一月的时候继续。
- - -
English: Sorry I have a lot of things to do for a while. Perhaps I will continue the translation project some time on this December or January 2019.
- - -
P.S. @Ben987 When I back to this project I wish we can talk in a Discord channel then, 'cause I don't know too much about slangs.

**Comment by Ben987** [comment]
It's fine, thanks for your work, I appreciate :)

Maybe someday I'll open a discord channel, I'm not sure yet.

**Pull request merged**
