### PR TITLE
Update Email

### PR DESCRIPTION
**Pull request by Atasly**
requires Server PR [#24](https://github.com/Ben987/Bondage-Club-Server/pull/24)

allow players to update their email linked to their account.
useful for people who : 
- forgot to/didn't setup an email address
- have stopped using the email address
- wants to delete some digital footprints

### CODE REVIEW

**Comment by Ben987** [comment]
For security reasons, we don't send the email back to the client when he logs, so the field will always be empty by default.

Wouldn't it create confusion for players to see an empty field all the time?  I would think that saving the email doesn't work myself if it always comes back blank.

Thanks!

**Comment by Atasly** [comment]
added a "Your email has been updated !" message in the input box after clicking on the button

**Comment by Ben987** [comment]
What I meant is: When players will open the screen, they will always see a blank email, and they will think that their email isn't saved on the server.

And they will report bugs telling us that their email isn't saved on their account.

**Comment by EveFerox** [comment]
Maybe have a "email linked" or "no email linked" indication somewhere?

**Comment by Ben987** [comment]
Yes, something like that.  The player must know that an email is linked to his account and we do not show that email for security reasons.  Try to make it as clear as possible so we don't get tons of questions and bug reports.  Thanks :)

**Comment by Atasly** [comment]
added "No email saved, write here to add one."
and "An email is linked, write here to update it."
depending if an email is linked, or not, to the account

**Comment by Ben987** [comment]
Should we add another validation to prevent hacking?  Like requesting the entry of the first email before overwriting with the second one?

**Comment by Atasly** [comment]
reworked a little how it works, there is now two input fields. one for current email and one for the new one. 
if no email is detected, a message "No email saved, write here to add one" is in the second box.
once the button update email is clicked, if the current email is the same as the one saved, then we overwrite it by the new one. and send a message to the client about the success, or the failure, of the operation.

**Pull request merged**
