### PR TITLE
Refactoring SpeechGarble

### PR DESCRIPTION
**Pull request by witcher2**
Started refactoring.
Also adding documentation to it.

### CODE REVIEW

**Comment by Ben987** [comment]
Sorry, I cannot accept this.  Please don't push any console.log() to the production environment.  Also, none of the code has this kind of documentation yet, it's not needed right now.

**Comment by witcher2** [comment]
I dont expect you to accept this yet, since its not finished. Once done all the console.log() 's will be gone.

**Comment by Ben987** [comment]
Please don't do any pull request to the master branch if it's not ready.  Use your own branch, it will save me time.  Thanks.

**Comment by witcher2** [comment]
okay then, will close this and make a new one then once finished

**Pull request closed without merging**
