### PR TITLE
Naked apron

### PR DESCRIPTION
**Pull request by Ayesha-678**
Added a Naked apron outfit, Will be making a skimpier version soon~

### CODE REVIEW

**Comment by Ben987** [comment]
Since it's the maid apron, why do you call it "Naked Apron"?  Could you rename as "Maid Apron" and give it with to the player when you become a maid?  Thanks a lot.

**Comment by Ayesha-678** [comment]
I suppose I can do that, it might take a bit longer though for me to figure out though.

**Comment by Ben987** [comment]
Sure.  Take your time :)

**Comment by Ayesha-678** [comment]
I think I’ll close these pull requests, as I made some mistakes when making the assets, so I think I’ll just completely remake everything, I’ll have it done ASAP!

**Pull request closed without merging**
