### PR TITLE
Fix: Gag layering and vacbed

### PR DESCRIPTION
**Pull request by SandrineBC**
Fixed the priority of the following gags  to 50 so they are shown **over** the layer of the vacbed:
- dildo gag
- duster gag
- gas mask gag

That fixes issue [#878311](http://www.hostedredmine.com/issues/878311)

### CODE REVIEW

**Comment by Ben987** [comment]
Thanks!  But why are you duplicating the GasMaskGag and WebGag items with different values?  Shouldn't you edit the current values?

**Comment by SandrineBC** [comment]
Hmm, I'll look into it. That seems not to be the case on my side...

**Comment by SandrineBC** [comment]
Ben, double checked and there are no duplicate values now anymore, neither in my local files, nor in the committed one.

**Comment by Ben987** [comment]
Thanks!  But this creates conflicts with other pull requests, can you review to make sure everything works?  Thanks a lot.

**Comment by SandrineBC** [comment]
I re-checked after merging in the current master-branch. All gags work still as expected.

**Comment by Ben987** [comment]
Great!  Thanks a lot.  I will test it soon.  Cheers :)

**Pull request merged**
