### PR TITLE
New Front Hair alts (ALL CREDIT TO AKITA AND GATETREK ON DISCORD)

### PR DESCRIPTION
**Pull request by Ayesha-678**
New front hairs, redrawn from the original hairs.

ALL CREDIT GOES TO AKITA ON THE DISCORD SERVER! THEY DREW THE NEW HAIRS, I JUST ADDED THEM IN WITH PERMISSION! SO PLEASE DON'T CREDIT ME!
Also credit gatetrek too for testing!

### CODE REVIEW

**Comment by ace-1331** [comment]
Think they said to credit gatetrek too for helping with testing  ^

**Comment by Ben987** [comment]
Since they look similar to what we already have, should we remove the previous models?  To prevent cycling in 28 styles.  Or maybe we could do a survey on that.  Thanks.

**Comment by Ayesha-678** [comment]
Hmm, I do agree they look similar, Maybe do a survey?

**Comment by ace-1331** [comment]
many already said they wanted to keep the old ones in discord, I think it would only be fair to remove thr few that are almost identical.. some are a bit too different. Overall, the quality is way higher though

**Comment by Ben987** [comment]
Thanks everyone!  This looks great.

**Pull request merged**
