### PR TITLE
Reverse Bunny Suit

### PR DESCRIPTION
**Pull request by Kitsune-hellfire**
A new suit, the Reverse Bunny Suit, made it so that it can be used as a suit under clothing, meaning its able to combined with the bunny cuff accessories, allows access to the naughty bits.
Im hopeing to get this in the before the beta ends
If added to the club, please credit it under my club name "Kirsty"

### CODE REVIEW

**Comment by Ben987** [comment]
Thanks!  I can't review it now because I'm preparing the next version but I'll get to it when all the hot fixes will be done for that version.  Cheers :)

**Comment by Shiranui-Izayoi** [comment]
So I don't suppose it would be possible to include a clothes version of this as well? I would love to be able to combine it with say the seethrough suit or other such things? 

I know it wouldn't be useable with the bunny accessories but wouldn't it just be possible to add them to the now existing ClothAccessory items?

**Comment by Kitsune-hellfire** [comment]
it would be possible to add them to the cloth and sock sections, should only be a few minutes of copy and paste, with testing to see if it all appears fine, ive also moved the bunny cuffs into the accessory section already with this pull

**Comment by Shiranui-Izayoi** [comment]
Cool thanks for the quick reply I can't wait to see it in game we can always use more outfits like this.

**Comment by Kitsune-hellfire** [comment]
@Ben987 added the suit parts to clothing (Cloth and Socks) as well following the above quick chat, now allows for more customization with the suits

**Comment by Ben987** [comment]
Hi.  Why are you updating these files: BunnyCollarCuffs_*.png  ?

There doesn't seem to be any changes to the files but they are in your puil request.

Thanks.

**Comment by Kitsune-hellfire** [comment]
the update to them was to move them from "Cloth" to "ClothAccessories", making them usable with all of the clothing

**Comment by Ben987** [comment]
Awesome!

**Pull request merged**
