### PR TITLE
Ghostlist block whispers

### PR DESCRIPTION
**Pull request by Atasly**
modified some texts to better represent PR [#BCS27](https://github.com/Ben987/Bondage-Club-Server/pull/27 ) (untested)

### CODE REVIEW

**Comment by Ben987** [comment]
Whispers are not already ghosted?  The client outputs them?  I'll have to test that.

**Comment by Atasly** [comment]
they are- but they are still received. and some people blacklist others but are still up to listening/talking to them.
the main idea of this little fix was to move everything regarding messages to ghostlist and everything about actions in blacklist

**Comment by Ben987** [comment]
Should ghosting return a message from the server though?  Maybe we could do a quick Discord survey on that one.  We'll see what players think.

**Comment by Ben987** [comment]
Thanks!  I'll take it but I'll modify it later.  Adding someone to your ghostlist will also add it to your blacklist.  And the server whisper block will be removed.

**Pull request merged**
