### PR TITLE
Refactor: Item arms leather cuffs to extended items

### PR DESCRIPTION
**Pull request by SandrineBC**
# Summary
This PR refactors the leather cuffs for the arms to use the extended item script.
To keep this item consistent with the others, several files had to be renamed (and added)...

### CODE REVIEW

**Review by elliesec — APPROVED** [review]
As Nina mentioned, it might be worth looking at making `HasType` available at the asset level. Combining that with `AllowPose` would probably let us achieve the same thing with fewer assets. But this is an improvement for now!

**Review by ace-1331 — CHANGES_REQUESTED** [review]
#1396 Adds HasType on the asset layer to allow phasing out `Restrain` , if you merge and start from there, you can keep all images as they were before, looks good otherwise ^^

**Review by ace-1331 — CHANGES_REQUESTED** [review]
All good when it comes to the first comment.

But before we merge, something from the singleplayer also needs to be adjusted ->
`SarahSophiePreparePunishCharacter` and `SarahSlaveLockedCuffs` both need to use type instead of Restrain now.

This PR is also dependent on the fix in #1414

**Comment by SandrineBC** [comment]
Problems in `Sahrah.js` resolved. How did you spot that one?

**Comment by ace-1331** [comment]
Was already aware of it, but remembered when doing a projectwide search for .Restrain when I realized we were about to get rid of it

**Review by ace-1331 — APPROVED** [review]

**Comment by ace-1331** [comment]
After merging #1336, I'm going through PRs to check what might conflict/be missing.

When you resolve the conflicts, please make sure the items retain the proper SetPose/AllowPose/AllowActivePose, etc. set in 1336 as it appears this PR might change some of the same lines. It looks like you just need to add` HasType: false` to the incoming change, however please double check the type array to make sure they all set the proper pose and block the pose menu

**Comment by SandrineBC** [comment]
Everything works fine.

**Pull request merged**
