### PR TITLE
fix and another collar item

### PR DESCRIPTION
**Pull request by gatetrek**
CattleProd was being sold as a racket so change it
added a new collar not so sure on the name yet so might change later

### CODE REVIEW

**Comment by FeuertinKira** [comment]
Not sure about the priority change for the full blindfold. It will look a bit better with the larger coverage gags, but it will also look weird with a few other of the gags. E.g. tape, ring gag, spider gag, cloth stuffing, chopstick, carrot will all look a little bit weird when sitting above the blindfold.

**Comment by gatetrek** [comment]
that blindfold looks like be touching right to the face so be odd that a ball gag gets covered by it

**Comment by Ben987** [comment]
Good catch.  Thanks for the pull request.

**Comment by FeuertinKira** [comment]
Well now it will make it so that the mouth portion of gags like the ring gag will appear to sit on top of the blindfold which is even more odd. technically it also clips slightly into the balls of the ball gags now

**Pull request merged**
