### PR TITLE
little change

### PR DESCRIPTION
**Pull request by gatetrek**
new collar added.
add the way for people to switch their collars at the club management but tree are missing from the owner from doing it maybe a next button to switch like the spanking toys could be useful there

### CODE REVIEW

**Comment by FeuertinKira** [comment]
Odd, what happened to "prefer to ask the person if was ok to use there's"?

**Comment by gatetrek** [comment]
if old stuff of mine never cared unless something just added what like be for lovers out there without a collar placed on them by there mistress.
and thought do it to you like semi payback I guess could call it >w<

**Comment by FeuertinKira** [comment]
Actually, it's called hypocrisy.

**Comment by Ben987** [comment]
Very nice!  Doesn't having 937 for MouseX position interfere with the clickable character zones?  I'll have to test it.  Thanks a lot.  Cheers.

**Pull request merged**
