### PR TITLE
Feature: Lovers Vibrator (new item)

### PR DESCRIPTION
**Pull request by elliesec**
# Summary

Adds new "Lovers Vibrator" and "Lovers Remote" items to the game.

## How they work

* The Lover's Vibrator can only be added to a character by one of their lovers
* When added, the vibrator is given a member number belonging to the player that added it
* A player may only change the settings on the vibrator if they own the lovers remote, are the lover of the character it is equipped on _and_ their member number matches the member number on the vibrator
* _Anyone_ may remove the vibrator (as it is not a lockable item), provided it is not blocked by another item
* The remote is subject to the usual owner rules:
    * Confiscating remotes will confiscate the player's lovers remote
    * Blocking the player from buying remotes will prevent the shop from selling the lovers remote to the player

## Implementation

The changes that were made in order to implement this are summarised below:

* Adds two new properties to assets:
	* `CharacterRestricted` - causes an `ItemMemberNumber` property to be added to the item when it is equipped, which records the member number of the player that added the item, or -1 in the case of an NPC
	* `AllowRemoveExclusive` - can be added to a `LoverOnly` or `OwnerOnly` item to allow any player to remove it, regardless of whether or not they are the character's lover/owner
* Modifies the `CharacterAppearanceSetItem` function to take an optional `ItemMemberNumber` parameter, used to set an `ItemMemberNumber` property for items with the `CharacterRestricted` flag
* Modifies all usages of `CharacterAppearanceSetItem` to handle the modified function signature
* Modifies the `InventoryWear` function to take an optional `MemberNumber` parameter, to be passed to the `CharacterAppearanceSetItem` function
* Modifies all usages of `InventoryWear` to handle the modified function signature
* Refactors remote usage checks in `Dialog.js` into a common `DialogCanUseRemote` function

## Testing

I believe that I've tested the new items and functionality quite thoroughly.

* Players that are not lovers of a character cannot control their lovers vibrator
* Players that _are_ lovers of a character cannot control their lovers vibrator _unless their member number is on the vibrator_
* Players that are not lovers of a character cannot add the lovers vibrator to them
* Anyone, including the player themselves, can remove the lovers vibrator, provided it is not blocked by another item
* The lovers remote is confiscated when a player's owner activates remote confiscation
* The lovers remote cannot be bought from the shop if the player's owner has activated the rule blocking them from buying remotes
* The vibrator can only be added to or controlled on NPCs if they are the lover of the player
* The vibrator cannot be controlled with a standard vibrator remote
* Standard vibrators cannot be controlled with the lovers remote

## Assets

Below is an image containing a preview of the various new assets.

lovers-vibrator-wip-8

### CODE REVIEW

**Comment by Ben987** [comment]
In "CharacterAppearanceSetItem", we should not set Property unless we need to set a property or a member number.  Adding a Property and MemberNumber and setting it to null most of time will increase online traffic for nothing.  Thanks.

**Comment by elliesec** [comment]
Hi Ben.

I've checked out the network packets that get sent, and there is currently no difference between packets in the current game and packets on this branch, unless the `CharacterRestricted` flag is set. Note also that if the `CharacterRestricted` flag is not set, `Property` will actually be set to `undefined` rather than `null`:
```js
Property: ItemAsset.CharacterRestricted ? {ItemMemberNumber: ItemMemberNumber == null ? -1 : ItemMemberNumber} : undefined
```
This would _usually_ cause `Property` not to be sent in the websocket packet. However, the existing code in `ChatRoomCharacterItemUpdate` is actually always setting the property to `null` in the current game regardless (note that this is code that I _haven't_ changed):

```js
function ChatRoomCharacterItemUpdate(C, Group) {
	if ((Group == null) && (C.FocusGroup != null)) Group = C.FocusGroup.Name;
	if ((CurrentScreen == "ChatRoom") && (Group != null)) {
		var Item = InventoryGet(C, Group);
		var P = {};
		P.Target = C.MemberNumber;
		P.Group = Group;
		P.Name = (Item != null) ? Item.Asset.Name : null;
		P.Color = ((Item != null) && (Item.Color != null)) ? Item.Color : "Default";
		P.Difficulty = SkillGetWithRatio("Bondage");
		P.Property = ((Item != null) && (Item.Property != null)) ? Item.Property : null;
		ServerSend("ChatRoomCharacterItemUpdate", P);
	}
}
```
This will always set the `Property` to `null`, even if no `Property` is set.

If you'd like, I can raise a separate pull request to prevent `Property` from being sent in `ChatRoomCharacterItemUpdate` if it's not defined. Or I could bundle that change in with this one.

As a comparison, here's a websocket message that is sent in the current live game for adding an armbinder to a character:
```json
[
    "ChatRoomCharacterItemUpdate",
    {
        "Target": 6101,
        "Group": "ItemArms",
        "Name": "LeatherArmbinder",
        "Color": "#075606",
        "Difficulty": 0,
        "Property": null
    }
]
```
And here is a websocket message that is sent in my local version of the game for adding an armbinder to a character:
```json
[
    "ChatRoomCharacterItemUpdate",
    {
        "Target": 1,
        "Group": "ItemArms",
        "Name": "LeatherArmbinder",
        "Color": "#404040",
        "Difficulty": 10,
        "Property": null
    }
]
```

I'm happy to make an additional modification to remove the `"Property": null`, but I'd argue that it shouldn't really fall within the remit of this pull request. Let me know what you'd like me to do.

**Comment by elliesec** [comment]
Hi Ben. As a follow-up to my earlier comment, I've raised the mentioned change in the separate PR #1137. This should reduce the amount of data being sent through the websocket for any item update with no impact on gameplay.

**Comment by elliesec** [comment]
Hi Ben. As an update on this, since merging #1137 I've rechecked the packets being sent in this branch, and can confirm that no unnecessary fields are being sent. The only time the `Property` field gets sent at all is when the Lovers Vibrator is equipped.

This is an example of the packet that gets sent when equipping a vibrator that isn't the Lovers Vibrator (note no redundant `Property` field):

```json
[
    "ChatRoomCharacterItemUpdate",
    {
        "Target": 1,
        "Group": "ItemVulva",
        "Name": "ClitoralStimulator",
        "Color": "#8a00d1",
        "Difficulty": 10
    }
]
```

And this is an example of the packet that gets sent when equipping the Lovers Vibrator:
```json
[
    "ChatRoomCharacterItemUpdate",
    {
        "Target": 1,
        "Group": "ItemVulva",
        "Name": "LoversVibrator",
        "Color": "#790c0c",
        "Difficulty": 10,
        "Property": {
            "ItemMemberNumber": 2
        }
    }
]
```

**Comment by Ben987** [comment]
Can you change the "let" for "var" ?

Also, that code structure seems a little strange to me:

typeof Property.Intensity === "function" && (Property.Intensity = Property.Intensity());
typeof Property.ChangeTime === "function" && (Property.ChangeTime = Property.ChangeTime());
typeof Property.LastChange === "function" && (Property.LastChange = Property.LastChange());

It does the same as: if (typeof ...) Property.X = X(); ?

**Comment by elliesec** [comment]
Hi Ben, no problem, I'll change the let (just force of habit, looks like it slipped in).

And you're correct, the `condition && doSomething();` is a shorthand for `if (condition) doSomething();`. I can change them to if statements if you'd prefer (there's no functional difference).

**Comment by elliesec** [comment]
Hi Ben - I've changed that let, and also moved the `&&` shorthands to `if` statements in case it confuses people.

**Comment by Ben987** [comment]
Awesome!  Yes, using regular IF will make it easier to read.  Thanks a lot, I will test it soon :)

**Pull request merged**
