### PR TITLE
Beep Sound

### PR DESCRIPTION
**Pull request by Atasly**
Plays a sound when a beep is received. 
Note : will only play a beep sound if there is no other beep sound playing
needs testing on mobile version

### CODE REVIEW

**Comment by Ben987** [comment]
Very nice.  Could you put some kind of parameter with it?  

Not everyone will want sound in the game so it would be nice to be able to activate or deactivate it.

**Comment by Atasly** [comment]
I've begun working on an another feature that would need to save a setting so I'll look into that.

**Comment by Ben987** [comment]
Excellent, having a parameter for it will be a lot more convenient.  We could also use that parameter later when we have moans, whip sounds, etc.  Thanks.

**Comment by Atasly** [comment]
Created a a new set of variables (inspired by adokilume's work) for futures settings on first screen of preferences. Audio is now togglable and turned off by default.
still needs testing on mobile

**Comment by Ben987** [comment]
That looks great!  I will test it soon and let you know if everything works on my side.  Cheers!

**Pull request merged**
