### PR TITLE
Fix typos in the pleasure panties' decrease message

### PR DESCRIPTION
**Pull request by zorgjbe**
Credit: Sidious

### CODE REVIEW

**Comment by Shiranui-Izayoi** [comment]
Damnit how did I manage to miss that. And for so long. Thanks for catching it.

**Comment by Ben987** [comment]
Thanks for that fix!

**Comment by zorgjbe** [comment]
@Shiranui-Izayoi Don't sweat it, as long as there's text, there's typos 😅. Thanks for the merge!

**Comment by zorgjbe** [comment]
Well, I'm OCD-triggered by the text system displaying `$name's` instead of `$names'` when $name ends in "s" (Hi Fonts) 😝. Localized text-wrangling is hard!

**Pull request merged**
