### PR TITLE
Chinese Translations for Maid Quarters

### PR DESCRIPTION
**Pull request by WWWWWWWWWWWWWWWWWWWWang**
Two new Chinese Translations for the Maid Quarters part.

### CODE REVIEW

**Comment by WWWWWWWWWWWWWWWWWWWWang** [comment]
How can I fix this conflicting : (

**Comment by Nina-1474** [comment]
You need to merge the Ben987 master into your master and resolve the conflict.
The conflicting lines are actually your own lines from a previous PR. To avoid this in future, either merge often or better yet look into creating branches and PR'ing them instead of the master.
(Since this is a pretty simple conflict you could also hit the 'Resolve conflicts' button and remove the extra unwanted lines. But that won't always be the best solution for trickier conflicts so learning to merge is better)

**Comment by WWWWWWWWWWWWWWWWWWWWang** [comment]
Solved the issues caused by file conflict.

**Comment by Nina-1474** [comment]
Something went wrong there. If you look at the 'Files changed' tab, it's now reverting a lot of other recent changes.

**Pull request closed without merging**
