### PR TITLE
New item: Wooden Cuffs for hands and feet

### PR DESCRIPTION
**Pull request by TheGnarp**
Just a simple pair of wooden cuffs/stocks to secure your subbies' wrists and ankles in.

Future plans might involve converting them to an extended item to allow more poses.

### CODE REVIEW

**Review by ace-1331 — APPROVED** [review]

**Comment by ace-1331** [comment]
The hand cuffs do not stop you from applying item (no effect), it's the behavior for normal pose cuffs but for this one it might not be the desired effect? Im not sure if it's intended, but it isn't actually a bad thing.

Everything looks good

**Comment by TheGnarp** [comment]
Mhhh... good point!
I'll play around with it a little more and I too have the feeling I want it to be a little more restrictive.
Any other opinions are of course very welcome!!

**Review by elliesec — COMMENTED** [review]
All looks good, and they make a very satisfying "thunk" sound! I'll hold off on approving until you've decided whether you want to add the extra restrictions to them or not. Feel free to ping me when you've decided one way or the other.

**Comment by TheGnarp** [comment]
Who am I kidding?! I prefer my vict... uh, _guests_ to be more helpless anyway.
Thanks for pointing that out, guys, and thank you for the awesome service to wait until I made my mind up!
^_^

**Review by elliesec — APPROVED** [review]
Tested an working. Looks good!

**Pull request merged**
