### PR TITLE
Typed Item Custom Dictionary + Web refactor

### PR DESCRIPTION
**Pull request by ace-1331**
**Depends on #2776 to have a proper asset check** 
(This PR is left as a draft while #2776 still is)

- added support for custom dictionary entries for Typed Extended Items
- refactored ItemArms Web to use as an example for this new possibility.

this PR will likely have minor conflicts with the rest, Ill resolve conflicts when necessary

### CODE REVIEW

**Comment by Ben987** [comment]
Same here, can you resolve and test again?

**Comment by ace-1331** [comment]
will merge #2776 after conflicts are resolved on that branch, then I'll resolve extra conflicts if there are any. Will comment again when it's ready

**Comment by ace-1331** [comment]
all set

**Comment by Ben987** [comment]
All that TS stuff is foreign to me, but if it helps you guys, it's all good.  Thanks for that piece of code :)

**Pull request merged**
