### PR TITLE
Allow KneelingSpread pose on the ItemNeckRestraints

### PR DESCRIPTION
**Pull request by zorgjbe**
This adds the needed stanza to the short chain, rope, and post.

### CODE REVIEW

**Comment by Ben987** [comment]
I think these were meant to prevent kneeling.  I'm not 100% sure though, anyone here has the answer?

**Comment by Jomshir98** [comment]
> I think these were meant to prevent kneeling. I'm not 100% sure though, anyone here has the answer?

They actually force kneeling (short rope leading to the ground).
This PR only allows sub to select whether they kneel normally (current behaviour) or kneeling with spread legs (new option).

**Comment by Ben987** [comment]
Alright!  Thanks for that one :)

**Comment by zorgjbe** [comment]
Yup, thanks for the clarification @Jomshir98, and for the merge @Ben987 👍.

**Pull request merged**
