### PR TITLE
Game toothpick

### PR DESCRIPTION
**Pull request by Uwnodi**
A new Game for the FirstSub in gambling room, available at gambling level 20.

The player and NPC take alternating 1-3 Toothpicks from a beginning stack of 15.
Whoever takes the last loses the game.

### CODE REVIEW

**Comment by Ben987** [comment]
This looks great!  Have you spoken with git4nick to make sure he's fine with adding a new game in his room?  You can contact him on DeviantArt.

**Comment by Uwnodi** [comment]
Um no.
Sorry, i didn't know that.

Cann he read this here?

**Comment by Ben987** [comment]
Let me check with him quick.  I will send him a DeviantArt note to make sure he's ok that we are adding stuff in his code.  Thanks.

**Comment by Ben987** [comment]
I couldn't reach git4nick at all.  I'll include the change, I guess he will like it.  Thanks :)

**Pull request merged**
