### PR TITLE
Pony harness gag fix

### PR DESCRIPTION
**Pull request by MoonlightGleam**
Updated the priority for the post, as it stood behind some items

### CODE REVIEW

**Comment by elliesec** [comment]
Presumably you'll also want to make these changes on the `ItemMouth2` and `ItemMouth3` versions?

**Comment by MoonlightGleam** [comment]
> Presumably you'll also want to make these changes on the `ItemMouth2` and `ItemMouth3` versions as well?

Cant we use something like CopyConfig for those?

**Comment by elliesec** [comment]
> Cant we use something like CopyConfig for those?

Afraid not at the moment. It's something I've considered, but the usage would have been limited, and we haven't really had any items that would benefit significantly from it up until now, where the sheer number of layers is obviously a lot of copy/paste code.

**Comment by Ben987** [comment]
Sure!  Thanks for these changes :)

**Pull request merged**
