### PR TITLE
More extended item refactor

### PR DESCRIPTION
**Pull request by ace-1331**
- moved ItemLegs DuctTape ClitRing, BondageBench, NoseRing, Cushion, InflatedBallHood, SpreaderMetal, HeavyLatexCorset, RoundPiercing, ButtPlugLock, AnalHook, ClitSuctionCup, NippleSuctionCups, ButtPump, LactationPump, CeilingRope, CeilingChain, InflatableLeotard, MetalCuffs, ItemArms Chains, ItemBreast Ribbons, ItemTorso Ribbons, ItemLegs Chains, ItemLegs HempRope, ItemFeet Chains, CryoCapsule & Coffin to the newer extended item system.
- added a new ChatSetting option to TypedItems to enable silent type changes
- added a missing hidden group to the InflatedBallHood

I know there'll be a hotfix period for a while, feel free to let this PR sit and merge the rest first, Ill resolve conflict when needed if necessary

### CODE REVIEW

**Comment by Ben987** [comment]
This one is huge, I'll get to it once I've tested the smaller ones.  Thanks!

**Comment by ace-1331** [comment]
Sure, no problem. I tested every item after doing them to check for missing dialogs, changed prerequisites and such. With how likely this is to create conflicts for those adding new options/items, I recommend not waiting too long to avoid mistakes from conflict resolution

**Comment by ace-1331** [comment]
Merged upstream/master and refactored ItemLegs DuctTape after #2757 was merged

**Comment by Ben987** [comment]
Alright!  It's time to test that big one.  Thanks a lot :)

**Pull request merged**
