### PR TITLE
New Clothing Type: Necklaces!

### PR DESCRIPTION
**Pull request by Ayesha-678**
Added a new clothing slot for necklaces! and added two necklaces to go along with it!

Edit: Make that three necklaces!

### CODE REVIEW

**Comment by Ben987** [comment]
That's a good idea :)

Can you make some of the necklace free so players have a few choices when they start?

Thanks!

**Comment by Ayesha-678** [comment]
Sure! No problem!

**Comment by Ayesha-678** [comment]
Alright, made two of them free~

**Comment by Ben987** [comment]
In Female3DCG.csv, there's no name for the new group.  Can you add one like for other groups?  Thanks!

Also, there's a conflict in Female3DCG.js, maybe with your previous request.  Thanks.

**Comment by Ayesha-678** [comment]
All fixed up!

**Comment by Ben987** [comment]
Are you sure you've used the latest version for this commit?  Lots of stuff from recent commits are getting removed.  Can you validate?  Thanks.

**Comment by Ayesha-678** [comment]
It seems a i messed something up, ill need to make a new branch >.>

**Pull request closed without merging**
