### PR TITLE
Feature: KinkyDungeon Clairvoyance Spell

### PR DESCRIPTION
**Pull request by fleisch11**
adds a spell that let's one see everything for five turns.
(great for teleporting behind walls)
feel free to change the stats for balancing

(i hope this is a good idea)

### CODE REVIEW

**Comment by Ben987** [comment]
@Ada18980 , would you like to review this pull request and let me know if it's something you'd like to add?  Thanks!

**Comment by Ada18980** [comment]
I would rather it be "you can see through walls for 3 turns" but I cant
review right now because I am on vacation

**Comment by Ada18980** [comment]
I am actually somewhat against this as it limits design space to be able to see across the entire map. The map is designed as a maze so revealing the whole thing will make it impossible t ok have secrets and such that take some investigating to discover.

They way I would rather do it is to highlight nearby walls or grant the ability to see through them for a short time (also ignoring blindfolds temporarily)

**Comment by fleisch11** [comment]
@Ada18980
first: by everything, i mean everything on camera (it just sets all the brightness to 3)
second: allright, i'll make it so walls dont effect the brightness

**Comment by fleisch11** [comment]
@Ada18980  how many turns do you think it should last? (i'm going with three for now)

**Comment by fleisch11** [comment]
@Ada18980 allright, everything is how you asked now, right?

**Comment by Ada18980** [comment]
I wont be able to playtest for a while due to being on vacation, but I'll let you know once I take a look at it.

**Comment by fleisch11** [comment]
@Ada18980 ok

**Comment by fleisch11** [comment]
@Ada18980 not trying to be impatient, but you haven't forgotten about this pull request. have you? (i can wait, just wanna make sure though)

**Comment by Ada18980** [comment]
> @Ada18980 not trying to be impatient, but you haven't forgotten about this pull request. have you? (i can wait, just wanna make sure though)

Yeah, Im not sure about this because it limits design space (having hidden loot that you have to look for). I haven't worked on Kinky Dungeon in a while, I'll consider it next time I am making new additions.

I also don't think the implementation is futureproof, it should be implemented using the buff system (similar to Shroud) to achieve the current effect.

I don't mean any offense, it's just that I prefer to keep a close eye on how things are implemented in Kinky Dungeon because it's a game with actual balance.

**Comment by fleisch11** [comment]
@Ada18980 allright

**Comment by fleisch11** [comment]
@Ada18980 allright

**Pull request closed without merging**
