### PR TITLE
New item: Pet bed

### PR DESCRIPTION
**Pull request by Codefreak64**
Adding a small bed for the four limbed subs,
adds to petplay and pet comfort.

1 item is added in the | ItemDevices | tab

### CODE REVIEW

**Comment by Ben987** [comment]
Thanks!  But there's a conflict with the current asset file.  Can you resolve the conflict and test again?

**Comment by Codefreak64** [comment]
oh my bad, i'll get on that asap

**Comment by Codefreak64** [comment]
hate that github adds code showing what you added, causing things to be conflicted.

great now an asset check failed?

**Comment by Ben987** [comment]
It all looks good now, thanks for the fix and the new item :)

**Pull request merged**
