### PR TITLE
Mermaid

### PR DESCRIPTION
**Pull request by Kitsune-hellfire**
made a "Mermaid Suit" for all the girls on the beach and at the pools

if added, please credit it under my club name "Kirsty"

### CODE REVIEW

**Comment by Ben987** [comment]
That's a good idea.  But why are you removing the "Base" from another item?  Thanks.

**Comment by Kitsune-hellfire** [comment]
fixed the issue, not sure what happened there but have re added the "base" line and removed and extra comma i found

**Comment by Ben987** [comment]
Thanks, but your pull request still removes the "Base" tag of the item.  Can you fix that?  Cheers :)

**Comment by Kitsune-hellfire** [comment]
fixed the issue and hopefully its back to normal

**Comment by Ben987** [comment]
Great!  I'll test it right now.  Thanks :)

**Pull request merged**
