### PR TITLE
insertion sort for appearance

### PR DESCRIPTION
**Pull request by Atasly**
rewrote the appearance sort function by using insertion sort
that will allow to have more than 50 layers of priority and finally get a proper layer system without any conflict if someone wants to work on it

### CODE REVIEW

**Comment by Nina-1474** [comment]
Hey Jenny, this appears to have dropped the check of Property.OverridePriority. Was that intentional?

**Comment by Atasly** [comment]
fixed it, was an error from me.

**Comment by Ben987** [comment]
Thanks, I've been wanting to do something like that for a while.

Can you use "var" instead of "let"?   We don't use let anywhere in the code right now.  Thanks

**Comment by Atasly** [comment]
done

**Comment by Ben987** [comment]
Awesome!  This will allow us to go beyond 50 for priorities.  Lets hope the numbers won't get too crazy though.  Cheers!

**Pull request merged**
