### PR TITLE
German Bondage Club: New Translations + Updates

### PR DESCRIPTION
**Pull request by adokilume**
Alright, here we go. All the new lines since the last Pull Request have been added/updated, plus we now have most of the minigames, all the rooms by GIT4NICK and wildsj, and the Shop (partial credit goes to @Dallun511 for that). Also, I went back and changed some translations I wasn't entirely happy with before, most notably what maids and head maids are called. Thanks to @Dallun511 and @Drussler1 for coming up with really helpful ideas!

### CODE REVIEW

**Comment by Ben987** [comment]
Wow!  You guys are my heroes, that was quick.  Thanks a lot.

I'm sure German players will be very happy, congrats.

**Comment by Drussler1** [comment]
that's right, it's fun to play it in German!

**Comment by adokilume** [comment]
@Ben987 First of all, welcome back! (A bit late, but I didn't get a chance to say that yet. ;) )

After a bit of uncertainty, it seems that I will be translating the remaining few files of the Club (using the ones Dallun511 posted in #99 as a base, of course). I noticed a few problems:

- The game doesn't seem to be loading translations for Female3DCG.csv, since it's neither a Dialog nor a Text file. This results in the clothing options and inventory items always being English.
- The Buttons on the top right when accessing your inventory (Remove/Cancel/Struggle/Unlock), aren't translatable because they're hardcoded in Dialog.js
- This isn't as important, but the "vs" in the Kidnapping Minigame intro is also hardcoded. Doesn't really matter for German, but maybe for other Languages. (Also, Text_Kidnap.csv has 3 columns instead of 2, due to a formatting error on line 48.)

I could probably fix the last one pretty easily, but is there anything you can do about the first two? Or should I just ignore them for now?

**Comment by Ben987** [comment]
Yes, I'll need to come up with a system to translate all of these captions.  I'll try to do it soon.

**Comment by Drussler1** [comment]
We could think about a walkthrough!

**Comment by Drussler1** [comment]
Moin moin and hello... since a while I can't sign up in the Bondage Club anymore! It always stands name and password are checked...?

**Comment by Ben987** [comment]
Yes, the github version won't be able to connect to the Bondage Club.  It will be fixed soon when I install the latest version.

**Comment by Drussler1** [comment]
But we have the online login page to login! A small question I still have the quest chapter 14 the texts of Mistress Sophie, are you already translating into German?

**Comment by adokilume** [comment]
@Drussler1 I started translating the Sophie chapter, but didn't have much time to keep working on it lately. I was going to maybe upload a general translation update later today, I could include the Sophie file I've done so far in there, if you'd like to take that one over? I'd just like it to stay in more or less the same style. If you want to discuss the details, you can message me on Discord (adokilume#1553).

**Comment by Drussler1** [comment]
I don't have a user account on Discord yet! I'd finish the translation first and you only need to have a look over it when it's done and change the text structure if it's not okay! can you give me the link to the file and where I can upload it again?

**Comment by adokilume** [comment]
Alright, I'll do that a little later, there's a few things I need to change on it first because it's out of date, and I'm also working on something else for the game, so it could take about 2 hours, sorry.^^'

**Comment by Drussler1** [comment]
With a good cup of coffee the day always starts great! Don't get stressed, we do it as a hobby! :)

**Comment by adokilume** [comment]
@Drussler1 Sorry it took so long, but I finally got around to cleaning up and fixing my files.^^' Here they are (ending with `_DE.txt`):
https://github.com/adokilume/Bondage-College/tree/club_de_10/BondageClub/Screens/Room/Sarah
You can download them if you open them, click on "Raw" and then save the files. Then just translate each pair, English on top, German below. The lines starting with `###` are just comments. If you place the files in the correct folder of the current version of the game, you can also use the file `BondageClub/_Translation/Tools/TranslationStatus.html` to check how much work is left to do. Sophie's file should be the most, but Sarah and Amanda also have some new lines.

Thanks in advance for your help! :D If you have any more questions, feel free to ask (in English or German). I'm more active on Discord, but GitHub works too.

**Comment by Drussler1** [comment]
Wenn du mal zeit hast, ich bin fertig mit der Übersetztung! [https://github.com/adokilume/Bondage-College/tree/club_de_10/BondageClub/Screens/Room/Sarah](url)

**Comment by adokilume** [comment]
Wie hast du sie denn bearbeitet? Normalerweise müsstest du die Datei(en) downloaden und es offline machen. Danach lädst du sie hier hoch, entweder in deinem eigenen Fork um selbst einen Pull Request zu machen (wenn du weißt wie), oder hier als Anhang, dann kann ich den Rest erledigen,

**Comment by Drussler1** [comment]
bandicam 2019-06-05 19-24-11-690

**Comment by Drussler1** [comment]
Ich bin dort auf dem Stift gegangen! 


bandicam 2019-06-05 19-28-15-319

Ich kann immer noch online drauf gehen. 
So großer nun erzähl mal wie kannst du drauf zugreifen?

**Comment by Drussler1** [comment]
[Dialog_NPC_Amanda_DE.txt.txt](https://github.com/Ben987/Bondage-College/files/3258400/Dialog_NPC_Amanda_DE.txt.txt)
[Dialog_NPC_Sarah_DE.txt.txt](https://github.com/Ben987/Bondage-College/files/3258402/Dialog_NPC_Sarah_DE.txt.txt)
[Dialog_NPC_Sophie_DE.txt.txt](https://github.com/Ben987/Bondage-College/files/3258403/Dialog_NPC_Sophie_DE.txt.txt)

Habe die texte! Dialog_NPC_Sarah muss ich noch mal machen aber sie ist Morgen fertig!

**Comment by adokilume** [comment]
Ah, alles klar. ^^ Das mit dem Stift hat mich echt verwirrt, sollte eigentlich nicht möglich sein weil in meinem Fork nur ich Zugriff haben sollte. Aber ok, dann können wir den Rest bis morgen klären. Entweder machst du selbst einen Pull Request an Ben, oder ich mache es und nenne dich als Autor, falls das einfacher wäre.

Kleine Anmerkung: Hast du die französischen Begriffe bei Sophie mit Absicht nach deutsch übersetzt? Es ist eigentlich eine Charaktereigenschaft von ihr dass sie manchmal französische Wörter benutzt, ich dachte wir würden das beibehalten.

**Comment by Drussler1** [comment]
Du kannst gerne ein Pull Request erstellen!Ich bin mit GitHub noch nicht so vertraut! 
Aber ups da schaue ich noch mal rüber ^^ dacht mir nix bei den französische Wörter! Aber stimmt es pass zu Sophie!

**Comment by Drussler1** [comment]
[Dialog_NPC_Amanda_DE.txt.txt](https://github.com/Ben987/Bondage-College/files/3258620/Dialog_NPC_Amanda_DE.txt.txt)
[Dialog_NPC_Sarah_DE.txt.txt](https://github.com/Ben987/Bondage-College/files/3258621/Dialog_NPC_Sarah_DE.txt.txt)
[Dialog_NPC_Sophie_DE.txt.txt](https://github.com/Ben987/Bondage-College/files/3258622/Dialog_NPC_Sophie_DE.txt.txt)
So bin doch gerade fertig geworden und die französische Wörter sind wieder mit drin!

**Comment by adokilume** [comment]
Ah, ok, klasse! ^^ Ich bringe gerade ein paar andere Dateien in Ordnung die leicht veraltet sind, dann kann ich die da mit einbauen. Ich sehe noch ein paar kleine Probleme, in Sophie's Datei scheint die Zeichenkodierung niht zu stimmen und alle Umlaute sind bei mir Fragezeichen, aber das ist nicht weiter tragisch, sollte ich schnell behoben kriegen. Ein paar der Zeilen muss ich wahrscheinlich leicht umschreiben weil sie zu lang sind, aber das sind nur 11, also auch keine große Sache. Alles zusammen sollte _allerspätestens_ dieses Wochenende fertig werden, vielleicht aber auch schon früher. Aber garantiert noch vor dem nächsten Spiel-Update. Vielen Dank für die Hilfe, das ging echt schnell! :D

**Comment by Drussler1** [comment]
Guten Morgen! Sehr schön das ich etwas helfen konnte.

**Pull request merged**
