### PR TITLE
more cow printed clothing

### PR DESCRIPTION
**Pull request by gatetrek**
adds printed socks, gloves, tail
added some horns, tail plug

### CODE REVIEW

**Comment by Nina-1474** [comment]
CowHorns has the Fetish tag twice.
And a heads up: some of the tail strap image changes are going to conflict with the split into layers under #1392.

**Review by elliesec — APPROVED** [review]
Looks good! There are some notable clipping issues with the gloves in the `OverTheHead` pose, although I imagine that's because they're an edit of the long gloves, which have the same issues anyway.

**Comment by gatetrek** [comment]
yeah it was but managed to remove most the clipping so both glove2 and the printed ones should be better now

**Comment by elliesec** [comment]
Nice, looks good!

**Review by ace-1331 — APPROVED** [review]

**Pull request merged**
