### PR TITLE
Old gas mask rework

### PR DESCRIPTION
**Pull request by ace-1331**
~~This PR includes #2762 to avoid a lot of conflicts, and should be merged after #2762 (this PR itself is much smaller)~~

- reworked/standardized the OldGasMask to leverage the new systems in order to remove what is no longer necessary. (Removed the extra items, merged it into a modular one with multicolor)
- removed the ItemHoodAddon group as it is no longer needed.

The person who made the original assets and I are quite happy with the result ^^ and I personally think it's nice to remove this type of clutter (ItemHoodAddon). I've had the intention to do this for a while, now was a good time.

### CODE REVIEW

**Comment by Ben987** [comment]
This one creates lots of conflicts with the previous PR, can you resolve them and test again?  Thanks :)

**Comment by ace-1331** [comment]
all set

**Comment by Ben987** [comment]
This one has another conflict.   Can you double-check?   Thanks.

**Comment by ace-1331** [comment]
all good, no other pr should conflict for now ^^

**Comment by Ben987** [comment]
Alright!  Yes, removing that extra slot is a great idea :)

**Pull request merged**
