### PR TITLE
Refactor: Duct tape on arms

### PR DESCRIPTION
**Pull request by SandrineBC**
# Description
This PR moves the duct tape on the player's arms to the extended item configuration.

# Testing
Was done on my local installation with one and two characters. Everything looked good on my side.

### CODE REVIEW

**Comment by Nina-1474** [comment]
The asset check failure is due to `Options` having properties not defined in the type. I think changing line 173 in AssetCheck_Types.js to this should fix it:
```JS
Options: "Maybe [{Name: String, SelfBondageLevel: Maybe Number, Prerequisite: Maybe [String], Property: Object}]", // Typed items
```

**Comment by jomshir98** [comment]
> The asset check failure is due to `Options` having properties not defined in the type. I think changing line 173 in AssetCheck_Types.js to this should fix it:
> 
> ```js
> Options: "Maybe [{Name: String, SelfBondageLevel: Maybe Number, Prerequisite: Maybe [String], Property: Object}]", // Typed items
> ```

I'm currently working on larger fix/refactor of assetcheck, I'll have PR ready soon.

**Comment by jomshir98** [comment]
Done, this PR will work after #2526 is merged.

**Comment by Ben987** [comment]
Absolutely!  Thanks again.

**Pull request merged**
