### PR TITLE
Adds chatroom help text for /help command and PgUp/PgDown shortcuts

### PR DESCRIPTION
**Pull request by elliesec**
This adds the `/help` command and the `PgDn`/`PgUp` shortcuts to the text displayed when using the `/help` command. This is complimentary to a pull request in the server code that will send a `ChatRoomHelp` message whenever a player joins or creates a chatroom.

Complimentary server PR: Ben987/Bondage-Club-Server#28.

### CODE REVIEW

**Comment by Ben987** [comment]
Instead of creating a server transaction for that, could you put the help text from the client side only and only once per session?  So don't do it when you enter a new chatroom, only in the first room you enter.  Thanks!

**Comment by elliesec** [comment]
Yep, that sounds sensible enough.

**Comment by elliesec** [comment]
Okay - that all happens client-side now - help is displayed the first time you enter the chatroom in session, no server calls. I've closed the corresponding PR for the server.

**Comment by Ben987** [comment]
Great!  I'll try it right now.  Thanks :)

**Pull request merged**
