### PR TITLE
Improvement: JSDoc comments added to Appearance.js

### PR DESCRIPTION
**Pull request by SandrineBC**
# Summary
@elliesec and me added JSDoc comments to the functions in `Appearance.js` to help with further development.
No functionality was added or removed.

The result of the JSDoc output can be found [here](http://www.hostedredmine.com/projects/bondage-club-issue-tracker/wiki/Appearance)

### CODE REVIEW

**Comment by Ben987** [comment]
Nice!  No need to put // if or // for though, the code is easy to read as it is.

**Comment by SandrineBC** [comment]
I removed the two closing brackets comments.

**Comment by Ben987** [comment]
Thanks!  This should be useful :)

**Comment by Ben987** [comment]
Check this change I've did a few days ago: https://github.com/Ben987/Bondage-College/commit/7a115643501776917eac61dc1494d4a1c26f235d

It allows to add difficulty combo from hands (4) + arms (4) + mouth (2).  Let me know if you like it or if we could add more to it.

**Pull request merged**
