### PR TITLE
Expanded Safeword functionality

### PR DESCRIPTION
**Pull request by Lucritius12**
This pull request expands the existing safeword with much requested additional functionality. Here is a list of changes:

**New Safeword toggle in Preferences**
Players who want a more "hardcore" experience can now opt out of using a safeword by disabling it in the preference menu. If you disable your safeword, you cannot turn it on again as long as you are wearing any restraints or chastity gear.
This allows players to play without safewords if they so desire, and the fact that they cannot re-enable the safeword while bound ensures that they are truly unable to use safewords to free themselves.

**New Safeword option: Full Character Release**
You can now use the safeword in a different way. If you find yourself stuck in restraints and nobody is willing or able to help you, you can use the safeword to completely free yourself of all restraints put on you, including even Owner locked restraints. Using the Safeword in this way also removes you from the Chat Room you were in and returns you to the main lobby - this ensures that this feature cannot be abused to "cheat" your way out of bondage without consequences. This new safeword mode does not adjust your item permissions, being returned to the Main Hall already prevents the player from being immediately tied up again.

**Altered Safeword dialog**
Whenever you use the Safeword Option in an online chatroom, you are now presented with the following dialog:

_(A safeword is serious and should not be used to cheat.  It can revert your clothes and restraints to when you entered the lobby, or release you completely.)_
Option 1: _(Revert Character.)_
Option 2: _(Release Character.)_
Option 3: _(Don't use Safeword.)_

Choosing "Revert Character" allows you to revert your character to the point when they entered the lobby:
_(This will revert your character's clothes and restraints back to how they were when you entered the lobby. Use this if you were forced into restraints against your consent. Are you sure you want to revert your character?)_
Option 1: _(Yes, revert Character.)_
Option 2: _(No, don't revert Character.)_

Choosing "Release Character" will trigger the new safeword functionality that fully releases your character and returns you to the Main Hall:
_(This will immediately release you of ALL restraints you are wearing and return you to the Main Lobby. Use this only if you are stuck in restraints and nobody can or wants to help you. Are you sure about this?)_
Option 1: _(Yes, I want to be released.)_
Option 2: _(No, don't release me.)_

**Additional Changes**
~All bodyparts in the Female3DCG.js file now have a new "Bodypart" attribute to make them easily identifiable by functions. This is used in a new function named "CharacterReleaseTotal(C)", which removes everything from your Appearance array except for *Clothing* and *Bodyparts*.
The new CharacterReleaseTotal function is used by the new Safeword option to make sure even locked nipple piercings and chastity gear are removed. This _does_ remove Slave Collars as well, though those will be re-gained upon reloading the game.~
EDIT: Removed unnecessary Bodypart attribute. The only other addition now is the new "CharacterReleaseTotal(C)" function which I use for the new "release" safeword and removes all items from you that aren't in the "Appearance" category. Slave Collars are kept, though slave collars that also act as gags (such as the Leather Corset Collar Gag) are reverted back to the default Slave Collar.

### CODE REVIEW

**Comment by Nina-1474** [comment]
Rather than needing to add Bodypart and Clothing properties, checking (Appearence[E].Asset.Group.Category != "Appearance") should give the same results.
Also Category could probably be changed to a boolean since it only ever has one of two values ("Appearance" or "Item"), but that's another matter.

**Comment by Lucritius12** [comment]
Excellent point, that code indeed works just as well. I've adjusted my pull request to remove the unnecessary inclusion of the Bodypart attribute

**Comment by Ben987** [comment]
This pull request creates a few conflicts with other pull requests that were merged recently, can you validate?  Please note that CommonIsClickAt is now MouseIn.  Thanks!

**Comment by Lucritius12** [comment]
Conflicts should be resolved!

**Comment by Ben987** [comment]
That looks great, thanks a lot, I will test it soon.  Cheers :)

**Pull request merged**
