### PR TITLE
Review and expansion of german translation

### PR DESCRIPTION
**Pull request by adokilume**
This is my first pull request ever, so I hope I'm doing everything correctly.

Corrected some mistakes in the german translation that I noticed (typos, CSV formatting etc). I also wrote a small script to check the width of each line of text (in pixels, not by character count) and tried to make them all short enough so they don't overflow their boundaries.
Finally, I decided to translate everything (hopefully) in C999, so the entire first chapter should now be playable in german, including menus and items.

If I find the time, I'd very much like to continue translating the next few chapters soon.

### CODE REVIEW

**Comment by Ben987** [comment]
This is HUGE!!!  Thanks a lot, you're a machine.  How would you like to be credited, is "adokilume" fine?

There's a little mistake with the fight text file, you're translating the English version instead of the Deutsche one.  No worries, I will correct it.

A huge thank you for your hard work, I'm sure the German players will appreciate :)

**Comment by adokilume** [comment]
Yeah, I noticed that mistake earlier today, whoops. I couldn't fix it easily at the time because I wasn't home, but luckily you saw it too. Though it seemed to me that particular file wasn't being used anyway since there's another one in the common folder?

And yes, the name is fine. To be honest, I don't really care that much anyway since this is an anonymous account and I just randomly made that name up on the spot.^^'

Thank you for your kind words, I'm having lots of fun both playing the game and translating it. :D

**Comment by Ben987** [comment]
Awesome!  It's been a while since I've worked on that part so I'm not sure if it's used anymore.

I'm glad you had fun with the game and enjoyed translating it.  Will you continue with Chapter 3 and up?

**Comment by adokilume** [comment]
I'm planning to. I'm actually almost done with Chapter 3 and should be able to finish at least 4 and 5 this week if nothing gets in the way. Right now though I'm trying to figure out how to get my fork up to date without making a mess in the commit history. Never done PRs before like I said.

**Comment by Ben987** [comment]
This is great news!  Take your time to make sure you don't lose any files on your side while working with the repo.  I'll be eager to try chapter 3 in German :)

**Pull request merged**
